### ISSUE TITLE
Icons/Labels "disappear" with dark theme?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [stevencohn/OneMore#794] opened 2022-12-10 03:16 UTC
**Describe the bug**

Seems random, but frequently, that these disappear:

![image](https://user-images.githubusercontent.com/39491297/206826439-5dc15a88-5539-4eb8-bbc9-3e88ac313967.png)

I've also seem them switch; e.g. the Snippets icon/label disappear, while the OneMore icon/label are visible.

**To Reproduce**

I just installed it, and use OneNote and it happens.

**Environment (if applicable):**
 - OneNote Version: 

![image](https://user-images.githubusercontent.com/39491297/206826498-340b5cfd-cffc-4dbe-ba4c-35d25418f858.png)
 
64 bit

 - OneMore Version:

![image](https://user-images.githubusercontent.com/39491297/206826535-1a6c7bd0-76a9-448f-882d-919d9c5e5cdb.png)

**Comment by stevencohn** [comment] 2022-12-10 12:02
Marking as duplicate of #795. When icons disappear like that, it means that OneMore has suffered an internal crash and can't recover.

**Closed by stevencohn** 2022-12-10 12:02 UTC
Labels: bug, duplicate
