### ISSUE TITLE
Update bug - "Error running command UpdateCommand. See log file for details"

### ISSUE THREAD

**Issue by Machiavelli09** [stevencohn/OneMore#858] opened 2023-01-30 19:26 UTC
**Describe the bug**
Issue with updating one more. 

**To Reproduce**
1. Go to "OneMore".
2. Click on 'About OneMore'
3. Click on 'Check for Updates'
4. Click on 'Update'
5. See error "Error running command UpdateCommand. See log file for details"

**Expected behavior**
Normally, it should close OneNote and update OneMore.

**Screenshots**
![image](https://user-images.githubusercontent.com/117470957/215574987-b8d5a5a8-ee1a-4ebc-b913-b6a84729589d.png)
![image](https://user-images.githubusercontent.com/117470957/215575017-4592c4ee-bf91-48f3-ae1b-f291bb9a71e0.png)

**Environment (if applicable):**
 - OneNote Version: Microsoft® OneNote® pour Microsoft 365 MSO (Version 2212 Build 16.0.15928.20196) 64 bits 
 - OneMore Version: Version 5.4.2
![OneMore Version](https://user-images.githubusercontent.com/117470957/215575721-fce4dfb5-99c0-4b75-9522-5b00a7e1e9a8.png)
![OneMore Error](https://user-images.githubusercontent.com/117470957/215575742-ab227903-ee88-433f-b472-5e357d6a308b.png)

**Additional context**
Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

**Comment by stevencohn** [comment] 2023-01-30 19:30
Duplicate of #823.

It was fixed in 5.4.4 - which means it will look broken when updating from 5.3.4 to 5.4.4. Until then, uninstall the addin manually, download, and install again.

**Closed by stevencohn** 2023-01-30 19:30 UTC
Labels: bug, unread
