### ISSUE TITLE
Search and select text only in the current page

### ISSUE THREAD

**Issue by erdeveloper** [stevencohn/OneMore#971] opened 2023-03-13 06:33 UTC
# New Feature

Search and simple **select** text only of all occurrences of searched text  in the current page for next formatting of selected text from OneNote formatting menus.

Search options could be for example:
- empty in 1st step and then
- Match case
- Match whole word only
- Match prefix
- Match suffix
- Regex

**Comment by stevencohn** [comment] 2023-03-13 11:35
Duplicate of #847

**Closed by stevencohn** 2023-03-13 11:35 UTC
Labels: duplicate

**Comment by erdeveloper** [comment] 2023-03-13 12:06
Sorry Steve, but this is not duplicate of #847 from my point of view. Issue is about selection of text only for your code change. Is not about  formatting such text. Also effort for implementation will be much lower as #847. Please think about issue ones more.

**Comment by stevencohn** [comment] 2023-03-13 12:57
Sorry I misunderstood. Your description says "...for next formatting of selected text from OneNote formatting menus".

If not that (which I think actually is a duplicate of #847) then what would you do once you've selected such text?

Note also that OneNote has a limitation that you can only have one contiguous selection range per paragraph. So if a match exists more than once in a single paragraph, only the first would be selected.

**Comment by stevencohn** [comment] 2023-03-19 20:23
I will consider this further. But quite honestly, this is the single most challenging request anyone could possibly have asked for. It's surprisingly more complicated than one would think. So I'll keep it on the list because I do think it's an interesting problem, but ultimately may not be worth the lift.
