### ISSUE TITLE
调整图片大小无法识别到图片 [Adjusting the image size] cannot recognize the image.

### ISSUE THREAD

**Issue by OriginBo** [stevencohn/OneMore#1243] opened 2023-12-31 02:34 UTC
# Problem to Solve

调整图片大小的功能，无法识别到不在内容框中的图片，即使选中图片也依然识别不到。
The function to adjust the size of the image cannot recognize the image that is not in the content box, even if the image is selected, it still cannot be recognized.

# To Reproduce

1. 把光标点到远离标题的地方
2. 插入一张图片，确保不在内容框中
3. 点击“调整图片大小”，提示没有图片；选中图片也是如此
1. Put the cursor far away from the title.
2. Insert a picture, make sure it's not inside the content box.
3. Click "Adjust image size," it prompts that there's no picture; selecting the picture also does the same.

# Expected Behavior

希望能识别选中的图片，不论它在不在内容框中
I hope to be able to recognize the selected image, whether it's in the content box or not.

# Screenshots

![image](https://github.com/stevencohn/OneMore/assets/56879486/c4c765cd-1a8f-481a-9db6-55351b47c9cd)

# Environment (if applicable)

 - OneNote Version: [ Office 2021 LTSC 64bit ]
 - OneMore Version [ OneNote 16.0.14332.20615 的版本 6.0.1 ]

**Comment by stevencohn** [comment] 2023-12-31 02:55
Duplicate of #1225.

Correct, background images are not resizable.

Will not fix.

**Comment by stevencohn** [comment] 2024-01-20 17:27
After consideration, included as part of #1258

**Closed** 2024-01-21 03:03 UTC
Labels: bug, released
