### ISSUE TITLE
Copy as Text and paste to other will be in confusion

### ISSUE THREAD

**Issue by mengxin523** [stevencohn/OneMore#1392] opened 2024-05-10 08:54 UTC
Hello,
When I use the mode of copying as text and pasting it elsewhere, I will find that the top and bottom lines of the text will automatically add carriage returns, resulting in confusion when pasting to the target and producing unexpected results
eg:
I just copy the text: RSXMB_AGG_XPI_ADMIN
and paste to else where:
![ShareX-2024-05-10 16-52-17 2453](https://github.com/stevencohn/OneMore/assets/39935125/f6669a7a-215d-4a69-8059-980c20952aef)
I select the first line and paste, but it will display in the second line!
![ShareX-2024-05-10 16-53-20 2454](https://github.com/stevencohn/OneMore/assets/39935125/563b402c-ba61-41dd-b6f9-195a76c757c1)

**Comment by stevencohn** [comment] 2024-05-10 10:36
Hello. From your screenshots above, it looks like you've selected those extra lines. But I can reproduce that it will add an extra line before the content that I've selected when selecting only one line. I'll look into that.

Alternately, you should be able to just use Ctrl+C to copy the content and paste into Excel, unless there is styling (bold, italic, color) that you do not want to copy over.

**Comment by mengxin523** [comment] 2024-05-10 11:41
> Hello. From your screenshots above, it looks like you've selected those extra lines. But I can reproduce that it will add an extra line before the content that I've selected when selecting only one line. I'll look into that.
> 
> Alternately, you should be able to just use Ctrl+C to copy the content and paste into Excel, unless there is styling (bold, italic, color) that you do not want to copy over.

No, I'm pretty sure I just selected the text and copied it, and inside the picture is the pasted result, with an Enter line before and after it,I am setting copy as text with the shortcut Ctrl+C
This problem is very difficult to use, please deal with it, thank you

**Comment by mengxin523** [comment] 2024-05-11 01:03
I wish to filter out the carriage returns above and below lines, otherwise pasting to a single text box will not paste, and pasting to Excel will produce the wrong line
Thank you

**Comment by mengxin523** [comment] 2024-05-11 01:15
![ShareX-2024-05-11 09-13-24 2475](https://github.com/stevencohn/OneMore/assets/39935125/041b38e9-6b28-4dee-9a2c-2e40e7735c05)

SEE

**Comment by stevencohn** [comment] 2024-05-11 01:16
I found a problem where Copy As Text would enter an extra blank line before the text. There should be no extra line after the text. Your picture shows that you selected the lines both prior and after your text. 

The fix should avoid anything other than what you've selected.

**Comment by mengxin523** [comment] 2024-05-11 16:43
I updated the latest version and found that now when pasting, the carriage return on the first line has been removed, which is good. But the text will be automatically followed by a carriage return!! Hope to remove them all!

**Comment by mengxin523** [comment] 2024-05-11 16:45
![Uploading ShareX-2024-05-12 00-44-53 2505.gif…]()
SEE

**Comment by mengxin523** [comment] 2024-05-11 16:46
![ShareX-2024-05-12 00-44-53 2505](https://github.com/stevencohn/OneMore/assets/39935125/85110f36-468c-4372-bbae-8fb09d9af268)
SEE

**Comment by stevencohn** [comment] 2024-05-12 13:51
The next release will have a couple of minor adjustments to _Copy as Text_. However, it's not going to do exactly what you need at all times for two reasons. First, the command must be fit for purpose for the majority of users and not specialized for specific use cases. Second, there are limitations in what OneMore can "see" on a OneNote page.

For example, the following two selections appear identical to OneMore. There is no way to determine whether the user has selected the end of line character so _Copy as Text_ must treat them the same - as if the end of line is selected.

![image](https://github.com/stevencohn/OneMore/assets/9964757/753a5b59-4431-4036-a920-24fd7039f952)

But it does fix mid-sentence selections:

<img width="144" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/4cb392e1-4d4c-4834-b2f9-d06f1eb7a49e">

will result in just the word "sentence" selected without a newline.

**Comment by mengxin523** [comment] 2024-05-13 00:54
Sometimes we copy a Shell command from OneNote to the Linux terminal, but if you automatically add an extra Enter line after the copy content, it will cause the command to be automatically executed after the copy is finished, which is very serious. Because copied commands often need to be slightly modified in the linux terminal to execute!
And every time I choose the text very carefully, try not to have a selection space after it, but unfortunately, pasting to the target will still be added with an extra Enter line!
I'm in favor of automatically adding an extra Enter line if the selected text is followed by a space, after all, users will copy multiple lines of text!

**Comment by mengxin523** [comment] 2024-05-13 01:07
![Uploading ShareX-2024-05-13 09-03-36 2517.gif…]()
SEE

**Comment by mengxin523** [comment] 2024-05-13 01:12
And if only the text is selected, not the final space, the copy function of the OneNote standard does not add any additional Enter lines; If the last space is selected, an Enter line is automatically added after it

**Comment by mengxin523** [comment] 2024-05-13 01:14
![ShareX](https://github.com/stevencohn/OneMore/assets/39935125/b543d763-4203-4c56-af75-812f8613e6a4)

**Comment by stevencohn** [comment] 2024-05-13 08:56
Then you should keep Ctrl+C as the built-in functionality and only use OneMore's Copy as Text when you want to avoid copying styles to applications that know about styles. Copying to a terminal should not copy styles so the built-in system Ctrl+C is what you want to use. You can often "paste as text" into various applications that know about such things as well.

**Comment by stevencohn** [comment] 2024-05-13 08:58
> And if only the text is selected, not the final space, the copy function of the OneNote standard does not add any additional Enter lines; If the last space is selected, an Enter line is automatically added after it

I understand. But OneMore doesn't have access to the OneNote internals so can't tell the difference unfortunately.

**Comment by mengxin523** [comment] 2024-05-13 09:43
> Then you should keep Ctrl+C as the built-in functionality and only use OneMore's Copy as Text when you want to avoid copying styles to applications that know about styles. Copying to a terminal should not copy styles so the built-in system Ctrl+C is what you want to use. You can often "paste as text" into various applications that know about such things as well.

I don't have much need to copy OneNote styles and paste them elsewhere, I usually just copy the text out and don't need styles

**Comment by stevenmcohn** [comment] 2024-05-13 09:51
When you copy content (either using Copy as Text or using the system Ctrl+C) it will create multiple copies of the content on the clipboard in various formats. If the content is text-based then, no matter which app, it will always add a raw text format.

Copying to a shell window will not copy the styles; it will copy the raw text.
To copy to Excel, you can use the Alt-H-V-M (Paste matching destination formatting)

Those are your workarounds while I consider whether the changes make sense for the majority of use cases. I understand your cases are important to you and I appreciate that. But I have to consider everyone and what their use cases are and have been. Thank you for your input.

**Comment by stevencohn** [comment] 2024-05-13 09:52
When you copy content (either using Copy as Text or using the system Ctrl+C) it will create multiple copies of the content on the clipboard in various formats. If the content is text-based then, no matter which app, it will always add a raw text format.

Copying to a shell window will not copy the styles; it will copy the raw text.
To copy to Excel, you can use the Alt-H-V-M (Paste matching destination formatting)

Those are your workarounds while I consider whether the changes make sense for the majority of use cases. I understand your cases are important to you and I appreciate that. But I have to consider everyone and what their use cases are and have been. Thank you for your input.

**Comment by mengxin523** [comment] 2024-05-13 11:38
I think it is important to note that this function is called copy as text, itself is copied text, there is no style!

**Comment by stevencohn** [comment] 2024-05-13 16:08
I am going to make some adjustments. This likely suites your needs. 

Note that this may cause others use cases to fail. Due to the lack of information form the OneNote APIs, OneMore simply can't cover all use-cases in intuitive ways, so some concessions are unavoidable.

**Comment by mengxin523** [comment] 2024-05-14 00:46
Oh Thanks !
The reason why I particularly need this Copy as text function is mainly because the content copied from the OneNote standard will become an image when pasted elsewhere, and OneMore also has a function called Copy as MarkDown, which in my opinion should contain style

**Comment by mengxin523** [comment] 2024-05-15 10:00
![ShareX-2024-05-15 17-54-16 2551](https://github.com/stevencohn/OneMore/assets/39935125/7d350680-b9bb-424d-864a-caa694d7612c)
NEW ISSUE
Text in the table ,and Copy as text will not work fine!

**Comment by stevencohn** [comment] 2024-05-15 10:12
This is fixed along with the work that will be released in the next version. The next version is not yet available.

**Closed** 2024-05-26 10:34 UTC
Labels: bug, released, high-priority

**Comment by mengxin523** [comment] 2024-05-27 07:59
I found that if the text in the table is copied, there will be a delay before it is pasted into other places. It will take several seconds before the pasted content is available. Before that, it is always the old content

**Comment by stevencohn** [comment] 2024-05-27 09:23
If the table is quite large, ostensibly any OneMore operation can be slow. Typically, reading a large page is quick for most operations. But tables make the page much more complex since OneNote presents it to OneMore as verbose XML. 

Writing to a large page, updating a large page, especially pages containing very large containers with complex tables and indents and drastically slow down due to the way the OneNote APIs work. This is a known problem and I've reported it to Microsoft but it doesn't seem to be anywhere on their priority list.
