### ISSUE TITLE
Enabling Context Menu options removes the OneMore addin ribbon item (and all features)

### ISSUE THREAD

**Issue by adamm1471** [stevencohn/OneMore#635] opened 2022-09-28 09:47 UTC
**Describe the bug**

On the latest version (5.1).. go to OneMore icon in the ribbon and navigate to Settings.  In the Context Menu, choose the Snippets Menu and check it. Click OK and follow the prompt to restart the OneNote application.   On restarting, the OneMore ribbon menu item is gone, as are all of the features.  To get this back, you need to go to your Roaming Profile (i.e. C:\Users\%username%\AppData\Roaming) and delete the OneMore folder (also lose all your previous settings). 

**Expected behavior**

Snippets menu to be enabled. 

**Environment (if applicable):**

- Windows 11, latest version of OneNote (Version 2209)

**Comment by stevencohn** [comment] 2022-09-28 11:39
Duplicate of #628

**Closed by stevencohn** 2022-09-28 11:39 UTC
Labels: bug, duplicate
