### ISSUE TITLE
Dialog placement not centered on OneNote, sporadically off screen altogether "lost"

### ISSUE THREAD

**Issue by sbennett18** [stevencohn/OneMore#227] opened 2021-05-12 17:07 UTC
**Describe the bug**
As seen in the sample screenshot below, dialogs occasionally appear on the wrong screen or more rarely off screen altogether with no way to retrieve them since the dialog cannot be focused with any keyboard shortcut that I have been able to come up with.
What the screenshot doesn't show is that the dialog _briefly_ flashes in the center of the OneNote window _then_ moves to wrong location.
Once focus is lost on the dialog (click any other window), there's no way to refocus the dialog.

Experimenting a bit more, the dialog seems to be placed properly centered when OneNote is located on my lower/smaller/primary monitor, but not when placed on my upper/larger/secondary monitor.

**Expected behavior**
OneMore dialogs centered on the OneNote window and regain focus when switching back to OneNote application.

**Screenshots**
![image](https://user-images.githubusercontent.com/1417401/118014514-ec4d2d80-b318-11eb-8a0c-64038ee368d1.png)

**Environment (if applicable):**
 - OneNote Version: `O365 Enterprise Version 2101)`
 - OneMore Version: `3.19.4`

**Additional context**
```
79904:4] Log restarted
79904:1] Running command AboutCommand
```

**Comment by sbennett18** [comment] 2021-05-12 17:11
Somewhat related--if I close OneNote while a OneMore dialog is open, I get the following OneNote error when I reopen OneNote:
![image](https://user-images.githubusercontent.com/1417401/118016480-1142a000-b31b-11eb-8f1f-d93d2ca87fcd.png)

**Comment by 1001QAdotNET** [comment] 2021-05-13 03:05
Re dialog showing on the wrong screen
I had a similar issue and I reported that here. 
In my case I  could not see the dialog simply because the dialog was hidden by other window or I switched that monitor via an HDMI switch to another PC. 
The dialog will show on your main screen.
If you have OneNote on a secondary screen this is why.
Not sure if Steven can fix that

**Comment by stevencohn** [comment] 2021-07-14 11:04
> Somewhat related--if I close OneNote while a OneMore dialog is open, I get the following OneNote error when I reopen OneNote:

How do you close OneNote while a OneMore dialog is open? I think only one dialog is not modal meaning most prevent you from closing OneNote while they are open. Are you killing OneNote in Task Manager? That can certainly get you into a funky state where the OneMore dllhost hosting process hangs around. You'd need to kill that process before restarting OneNote. The process ID is the first number on each line of the log file, e.g. 83584

**Comment by stevencohn** [comment] 2021-07-14 11:06
And I'm going to try to fix the placement issue....

**Comment by stevencohn** [comment] 2021-08-25 15:36
Interesting. I was able to try both cases and OneNote did shut down properly and I could restart it without issue. It could be that's it's taking a few seconds to shutdown but you're trying to restart too quickly? Not sure. But I'll keep an eye on it....

**Comment by sbennett18** [comment] 2021-08-25 15:39
You might be right about that. I just tried waiting ~30s after shutdown and did not get the error.

**Comment by stevencohn** [comment] 2021-08-25 15:41
You can watch the OneNote process in Task Manager. When it disappears, it's safe to restart

**Comment by stevencohn** [comment] 2021-09-20 23:24
I haven't been able to reproduce this. Until I have a repeatable pattern that I can use to show the problem, there's nothing I can do so closing this for now.

**Closed by stevencohn** 2021-09-20 23:24 UTC
Labels: bug, no-repro
