### ISSUE TITLE
Alt+C Shortcut for Colorize Command Fails with Error

### ISSUE THREAD

**Issue by dwillis77** [stevencohn/OneMore#1744] opened 2024-12-31 06:14 UTC
# Problem to Solve

Alt+C shortcut for colorize text command results in an error.

# To Reproduce

1. Select some text
2. Try to apply a colorize command via Alt+C, selecting the language and hitting ENTER (or pressing OK)
3. See the error message in the screenshot below (and text does not get colorized).

# Expected Behavior

Text should be colorized with no error.

# Screenshots

![image](https://github.com/user-attachments/assets/d0aeec5a-476f-4389-bb54-6186972742f5)

# Environment (if applicable)

 - OneNote Version: Office 365 version 2402 (build 17328.20648) semi-annual channel, 64-bit
 - OneMore Version: 6.6.1

# Additional Context

Relevant log entries from the OneMore log:

```
15|09:15:09.319| Running command ChooseColorizerCommand
15|09:15:22.189| Error running command ChooseColorizerCommand
15|09:15:22.189| System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.Commands.ChooseColorizerCommand.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.ChooseColorizerCommand+<Execute>d__2::MoveNext()
```

**Comment by stevencohn** [comment] 2024-12-31 12:15
Duplicate of #1660

**Closed by stevencohn** 2024-12-31 12:15 UTC
Labels: bug, duplicate

**Comment by dwillis77** [comment] 2024-12-31 17:24
Thanks, sorry I missed that duplicate.
