### ISSUE TITLE
ScanHashtagsCommand [Ctrl+ALt+F9] = Adds automatically new text to link (growth and growth)

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1684] opened 2024-11-26 13:29 UTC
# Problem to Solve

ScanHashtagsCommand [Ctrl+ALt+F9] = Adds automatically new text to link (growth and growth)

# To Reproduce

1. Add a link
   - Address: C:\
   - Text: Link #Test
1. Use keytip [Ctrl+ALt+F9] ScanHashtagsCommand
1. Text is now: Link #Test#Test#Test#Test

If your run [Ctrl+ALt+F9] again the text always growth and growth...

# Environment (if applicable)

 - OneMore Version 6.6.1
 - OneNote 16.0.18129.20158

**Comment by stevencohn** [comment] 2024-11-26 13:56
@nhwCoder  I'm not sure what you mean by this. Can you explain more or show a picture please?

> 1. Add a link
>    - Address: C:\
>    - Text: Link ##Test ##Test

**Comment by nhwCoder** [comment] 2024-11-27 14:07
You are right, I could describe it better

* Create a new empty page
* First: Add a link "aaa #bbb" that points to c:
* Then: Add below in next line the text aaa
This now looks like
![image](https://github.com/user-attachments/assets/ab73ac74-4f07-4866-b82b-d1107c372ae8)
![image](https://github.com/user-attachments/assets/e445327d-47c9-4986-9c6e-7fc965a7db68)

* Now: Run 2 or more times the keytip  [Ctrl+Alt+F9]
RESULT: To the link-text after the 2nd time and continuing always the text "#bbb" is magically added (no exception is shown)
![image](https://github.com/user-attachments/assets/bf97cbff-1688-47f2-aba4-1d9169a13920)

**Comment by stevencohn** [comment] 2024-11-29 17:10
Duplicate of, or will at least be handled by resolving #1683

**Closed by stevencohn** 2024-11-29 17:10 UTC
Labels: bug, duplicate
