### ISSUE TITLE
Feature request: Quick arbitrary tags

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#81] opened 2020-10-30 13:30 UTC
I would like to be able to right click on a page and add any arbitrary tag (type it) at that point
This should be added to the END of the tag list without disrupting the order of the current tag list and their shortcuts
The option should remember the last added tag
When the user right click and picks "Add tag" from the context menu he or she should be presented with a list of the most recently used tags and be able to select the wanted tag or simply hit enter and use the last used tag
If the user starts typing a tag the most similar tag should be selected. If no similar tag exists a new tag should be created and automatically added where the user clicked 

Currently to achieve a similar work flow you need to go through a sequence like this
-create the tag manually -a couple of clicks go into this
-when you need to use the tag you need to browse to the tag list and pick that tag

**Comment by stevencohn** [comment] 2020-10-31 00:53
Sorry if I'm mansplaining but.... OneNote tags are not based on text at all. You assign text labels to them but the labels are irrelevant. A tag is actually just a code, an integer, that is represented by the icon that appears next to the text block that you've tagged. Also, tags are applied only to "paragraphs"; this is why they can only appear to the left of a text block and not inline. Right-clicking in the middle of a sentence is no different than tagging the entire paragraph and OneNote doesn't remember that you clicked the middle of that sentence.

You can reuse the same icon, same code, and apply different text labels. Although they may appear to be unique in the drop-down, they are seen by OneNote as the same tag! This is because, as said above, each tag is only identified by its code and the label is irrelevant. So searching for star)A will also find all star)B, star)C, etc tags, because they're all the same.

Now, I can programmatically add any arbitrary tag/label to a page without affecting the defined list of tags shown in the Tags drop-down in the ribbon. 

Having said all that, your request isn't that far off from what the Find Tags button already does in OneNote. Albeit you can't create an index page of them. So, other than the index page, does any of this change your request? Are you really looking for keyword searching and management?

**Comment by 1001QAdotNET** [comment] 2020-10-31 04:52
yes I am looking for a keyword in my search and it will be important to find the exact ...
if they overlap that is not going to work
Yes I meant add tags to paragraphs -the paragraph I am clicking on

Not sure how the above can be implemented but I do think it would be a helpful feature
I think using html tags properties and searching for those could solve the problem

<div title="tags here" >

**Comment by stevencohn** [comment] 2020-11-16 16:08
Been looking at the OneNoteTaggingKit, OneNoteGem, Evernote, OneNote itself, .... What kind of requirements might you envision for tagging? 

Definition: I'm going to use **Label** here so it's not confused with OneNote's tags. This feature would be distinct from OneNote's tags (however internally would rely on tags because that does most of what is needed here; ramification being that searching for a tag will also show labelled pages)

1. Add one or more arbitrary labels to a OneNote page
2. Add the same label to other OneNote pages
3. Find all pages marked with one or a combination (subset or set) of labels
4. Further refine the search for pages that have some labels but not other labels
5. Show all pages that match the search criteria
6. Navigate to one of the pages in the result list
7. Create an index page of all pages matched

What I'm confused about is your point about applying labels to paragraphs... to what end?

**Comment by 1001QAdotNET** [comment] 2020-11-16 17:35
There is a couple of use cases I am seeing but they mainly come down to thee major use cases:
-find all the pages labeled with a tag or combination of labels (labeling like the blogs have tags for articles) **-this is a pure search feature** 
-label paragraphs: it would be great to be able to collect all the labeled paragraphs that are shown in the results in a different page (ex: important concepts -if I label my paragraphs this way I can run a search for a page or a group of pages or a section and extract like an abstract with the most important things for that section.  (**this is generating new content**)
 -creating aggregated To do lists (mark paragraphs with To do like tasks -which can be checked , and run a search to collect a list of them-that is your to do list -with either labels and links to paragraphs only , or labels and content of the paragraph (**this is to manage your tasks**)

**Comment by stevencohn** [comment] 2020-12-07 13:54
I know the tagging feature I've created isn't exactly what you describe above. It can't collate individual paragraphs. But it can collate tagged pages. 

Let me know if this is sufficient. 

Either way, I'm marking this as low priority for now

**Comment by stevencohn** [comment] 2020-12-07 13:56
Actually, as I'm reviewing open tickets, I came across #64 
Can you take a look at that? I think this one might be a duplicate of that.

**Comment by 1001QAdotNET** [comment] 2020-12-07 14:21
yes the other user is after similar things but I think he is interested in the ability to search using multiple tags;
He is not clear what he wants to do with the paragraphs and it is not clear if his search is in a page/section or notebook but he seems to ask a very similar thing

**Comment by MehsEzeerf** [comment] 2021-07-02 22:12
This request and this one https://github.com/stevencohn/OneMore/issues/225  for bidirectional linking kind of complement each other.  With the bidirectional linking ability searching from the standard OneNote search and limiting it to pages should pull up the page that has directional links to the referenced material.

**Comment by julie777** [comment] 2022-08-01 17:19
> Sorry if I'm mansplaining but.... OneNote tags are not based on text at all.

@stevencohn 
Based on my research tags are actually based on the text of the title and the symbol (number) and the other attributes. You can mix and match and create tags with different names and the same symbol or different symbols and the same names.

The real problem is that although there is a list of built-in and user defined tags for a given installation of OneNote, if you share or copy notebooks that list will not include any custom tags in the shared notebooks. The only way to get a definitive list of all tags is to search all notebooks. (I wrote a Onetastic macro for this and to allow me to update tag information based on tag attribute search.)  

ON find tags seems to use the tag name to group tags and has no way to search for symbol.

In addition, ON uses the symbol to determine which tags are tasks (meaning the can be in an not complete state).
Task Tag Symbols are not even sequential and consecutive.

I personally find the implementation of tags to be awkward and hard to use.

ON also changed the built-in tag definitions with different versions which adds to the confusion.

**Comment by stevencohn** [comment] 2022-09-20 23:45
Yes, you are correct Julie. Tags are defined by multiple attributes: name, index, type, and symbol as shown in the tables below. The primary key is the type attribute; this uniquely identifies the tag, not the symbol, since different symbols can be applied to tags with the same type value.

For instance, the "Num One" tag is shown like this by default:

<img width="60" alt="image" src="https://user-images.githubusercontent.com/9964757/191382570-e5626d2f-acd3-4f02-b90a-b37a06ae19a8.png">

and described in XML as
```xml
  <one:TagDef index="3" type="2" symbol="70" fontColor="automatic" highlightColor="none" name="Num One" />
```

but I can reuse the same type="2" but show it with a different symbol using the XML
```xml
  <one:TagDef index="0" type="2" symbol="142" fontColor="automatic" highlightColor="none" name="Foobar" />
```
which will appear like this

<img width="54" alt="image" src="https://user-images.githubusercontent.com/9964757/191382743-840408e1-08ae-441e-9c57-4a9f5781d77b.png">

Note that both the symbol and name are different but, since the type is the same, both OneNote and OneMore will treat them both at the same "classification" of tag.... tag type="2"

The index attribute is merely a page-local value used to dereference one:Tag elements on the page back to the corresponding TagDef, e.g.

```xml
<one:OE>
  <one:Tag index="0" completed="true" disabled="false"/>
  <one:T><![CDATA[That was a &quot;Number one&quot;]]></one:T>
</one:OE>
```

OneNote's Find Tag feature lets you sort tags in that panel in various ways, but this is just all smoke and mirrors because the real primary key is the tag type.

And of course, OneMore tagging feature is a (arguably valiant) attempt at creating a more extensible approach to tagging. It has absolutely nothing to do with OneNote's tagging system, which is both loved and hated by OneMore users. A lesson in "you can make everyone happy"

Having said all of that, I'm not sure where this leaves us an exactly which combination of requirements would help the majority of users. Maybe it's time to start over and rethink requirements.

And for reference...

<img width="615" alt="image" src="https://user-images.githubusercontent.com/9964757/191382343-774c24bf-c8a6-4696-b971-432a51602e6e.png">

**Comment by stevencohn** [comment] 2023-01-16 15:39
closing as stale. tagging needs "requirements"

**Closed by stevencohn** 2023-01-16 15:39 UTC
Labels: low-priority
