### ISSUE TITLE
Code Box Adds Additional Blank Lines Below

### ISSUE THREAD

**Issue by dwillis77** [stevencohn/OneMore#1311] opened 2024-02-21 19:49 UTC
# Problem to Solve

When adding a code box to existing code, it seems it will add a bunch of blank lines below it for some reason (appears to be roughly the same amount of blank lines as how many lines there were in the text that we added to the code box).

# To Reproduce

1. Type some existing text/code - the more lines you type, the more apparent the issue will be.
2. Select the text and add code box
3. See that the code box is added, but a bunch of whitespace is added below the code box as well (again, this appears to roughly correspond with how many lines of code were "boxed").

# Expected Behavior

Code box should be added with no change to formatting of text outside/around the box (i.e. no additional whitespace above or below the box).

# Screenshots

![image](https://github.com/stevencohn/OneMore/assets/52332611/a21fa847-dc90-4c46-9dc3-c46f9bce9cbd)

# Environment (if applicable)

- OneNote Version: O365, v2308 (semi-annual channel) build 16731.20504, 64-bit
- OneMore Version: v6.1.0

**Comment by stevencohn** [comment] 2024-02-21 20:17
This is, in fact, a duplicate of and will be solved by #1306

**Closed** 2024-02-21 20:17 UTC
Labels: bug, duplicate

**Comment by dwillis77** [comment] 2024-02-26 02:58
Interesting, ok, didn't realize the underlying root cause was the same for both. That works then. Thanks!
