### ISSUE TITLE
All OneMore actions change header colour in dark theme

### ISSUE THREAD

**Issue by geoff-B** [stevencohn/OneMore#206] opened 2021-03-25 05:02 UTC
**Describe the bug**
When OneNote is set to the "Black" theme, any OneMore action (e.g. search and replace, ToCase, Resize image, No Spell Check) causes the colour of headers to change to a darker blue colour.
The issue does not occur in light mode, though headers affected by this problem retain their unusual colour when changed from dark to light mode.

**To Reproduce**
1. In OneNote options -> General, set Office Theme to "Black"
2. Add headings to a page, at any level
3. Run a OneMore action
4. All headers (at any level) change to a darker blue colour.

**Expected behavior**
The header colours shouldn't be affected by these actions, as in light mode.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/38046772/112421486-ba462480-8cf4-11eb-8913-453540b5455c.png)

After:
![image](https://user-images.githubusercontent.com/38046772/112421503-c4682300-8cf4-11eb-94eb-7450326ed269.png)

Before/After, when changed to light mode:
![image](https://user-images.githubusercontent.com/38046772/112421864-86b7ca00-8cf5-11eb-8b51-8f7951262222.png)

**Environment (if applicable):**

- OneNote Version: O365
- OneMore Version: 3.19

**Comment by stevencohn** [comment] 2021-03-25 10:50
OneNote thinks it's smarter than I am (I know right!?) I've struggled with this for quite a while and haven't found a good solution. See my note about Dark Colors here https://github.com/stevencohn/OneMore/wiki/~-Developer-Notes

**Comment by geoff-B** [comment] 2021-03-25 16:55
So from what I understand, when a OneMore action is activated, everything on the page is copied out and put back, causing all the colours to be boosted another 25%?

**Comment by stevencohn** [comment] 2021-03-25 23:21
Yup. The API "sanitizes" all incoming content and there's nothing I can do about it. I've even tried to account for the 25% shift but that doesn't solve it either

**Comment by geoff-B** [comment] 2021-03-26 17:36
Would it be possible to re-apply each header after a OneMore action using the API? Doing this manually fixes the header colours.

**Comment by stevenmcohn** [comment] 2021-03-26 17:42
No, I can't drive the UI and I don't want to go down the path of automating the UI through forcing keystrokes, that just gets messy really fast. Not worth it

**Comment by geoff-B** [comment] 2021-03-26 18:17
I agree that forcing keystrokes would be a mess.

Been poking around the XML editor; after using a OneMore action in Dark mode, a style attribute is applied to each header that overrides the `QuickStyleDef` changes its colour to the washed out ones. 

This attribute can't be removed in the editor, or it will restore it self for some reason. However, the colour of the style attribute can be changed, and I managed to change it to the original colour as defined in the `QuickStyleDef`. This restores the colour and prevents the header from being affected by further OneMore actions, but needs to be applied to each subsequent header.

 The only downside to this is that the colour of the header would be the same for both light and dark mode, but this can be fixed by removing the style attribute in light mode (which it allows you to do).

I don't know if any of this can be done script-wise, but it looks pretty promising.

**Comment by stevencohn** [comment] 2021-03-26 18:35
Hm, now I'm kicking myself for not noticing that extra style attribute on the text itself. How did I miss that? I'll do some digging. Thanks!

**Comment by stevencohn** [comment] 2021-07-19 12:46
Using Microsoft® OneNote® 2016 MSO (16.0.14131.20278) 64-bit 
I can't seem to reproduce the problem.

It does exist in build 16.0.13127.21656 but there's a problem... The extra style attributes are not added until after OneMore updates the page. So to fix this, OneMore would need to re-read the page after it does its work, compare to look for any differences, and rationalize which changes are specific to this and which changes OneNote did because it was the right thing to do... and then update the page a second time if needed.

Seeing as how the problem seems to have resolved itself in the newer version, and the solution could be impractical or at least a performance hit, I'm going to close this ticket.

**Closed by stevencohn** 2021-07-19 12:46 UTC
