### ISSUE TITLE
Remove empty lines not working as expected in some situations

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#503] opened 2022-05-19 13:42 UTC
Here is the sample content that I have tried this on 
```
              <one:OE alignment="left" quickStyleIndex="2" selected="partial">
                    <one:T><![CDATA[IAM Guidelines &amp; Best practices]]></one:T>
                    <one:OEChildren selected="partial">
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[• Don’t use the root account except for AWS account setup]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[• One physical user = One AWS user]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[• Assign users to groups and assign permissions to groups]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[• Create a strong password policy]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[• Use and enforce the use of Multi Factor Authentication (MFA)]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[• Create and use Roles for giving permissions to AWS ser vices]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[• Use Access Keys for Programmatic Access (CLI / SDK)]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[• Audit permissions of your account with the IAM Credentials Repor t]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2" selected="partial" style="font-family:'Calibri Light';font-size:20.0pt;color:#464646">
                        <one:T selected="all"><![CDATA[•  Never share IAM users &amp; Access Keys]]></one:T>
                      </one:OE>
                      <one:OE alignment="left" quickStyleIndex="2">
                        <one:T><![CDATA[]]></one:T>
                      </one:OE>
                    </one:OEChildren>
                  </one:OE>
```

It seems that there is no way to use OneMore to remove lines like this
<one:T selected="all"><![CDATA[]]></one:T>

Am I missing anything ? This is related to #98 and #99

**Comment by stevencohn** [comment] 2022-05-19 14:30
Duplicate of #477 (there is some re-engineering work behind that ticket that will solve your problem here)

**Closed by stevencohn** 2022-05-19 14:30 UTC
Labels: duplicate

**Comment by CLITrees** [comment] 2022-05-20 03:39
Sorry it has been a while.
I am back at it hopefully I will remember all the tickets I opened and I will stop creating duplicates :-)
