### ISSUE TITLE
Second OneNote Process fails to load OneMore

### ISSUE THREAD

**Issue by seaspeak** [stevencohn/OneMore#1020] opened 2023-04-17 23:26 UTC
# Problem to Solve

Second OneNote Process fails to load OneMore. (

# To Reproduce

1. Run OneNote
2. Run OneNote again (don't close the first window)
3. Multiple errors, "The callback function "GetRibbonLabel" was not found, show.

# Expected Behavior

# Screenshots

![image](https://user-images.githubusercontent.com/8821870/232631621-629286bd-4cea-4468-886e-1de48883598b.png)

# Environment (if applicable)

 - OneNote Version: Office 2021 x64
 - OneMore Version: OneMore_5.8.4_Setupx64.msi

# Additional Context
After run OneNote twice and close them, I got the [OneMore.log](https://github.com/stevencohn/OneMore/files/11258405/OneMore.log)

**Comment by jasonjac2** [comment] 2023-04-18 05:17
I run multiple instances of OneNote 32 bit Version 5.8.4 with OneNote 16.0.16227.20280 and it is fine.
I would imagine that Steven will want an extract of the log file. 
About | Link at the bottom to the log file.
There is normally a clear point near the bottom where it goes wrong and you can see it.

**Comment by seaspeak** [comment] 2023-04-18 06:12
> I run multiple instances of OneNote 32 bit Version 5.8.4 with OneNote 16.0.16227.20280 and it is fine. I would imagine that Steven will want an extract of the log file. About | Link at the bottom to the log file. There is normally a clear point near the bottom where it goes wrong and you can see it.

Did you run the OneNote.exe (shorcuts) twice or use Ctrl+M? I have no problem with Ctrl+M.

**Comment by stevencohn** [comment] 2023-07-22 12:01
Closing as duplicate of #1058 which has more useful information

**Closed by stevencohn** 2023-07-22 12:01 UTC
Labels: bug, duplicate
