### ISSUE TITLE
Bidirectional linking feature！

### ISSUE THREAD

**Issue by yjcaaaaaaaa** [stevencohn/OneMore#1424] opened 2024-06-06 07:13 UTC
# Problem to Solve

Because I often use the method of connecting one place to several places, I can't know where the paragraph is linked by copying the paragraph link alone, and onemore's Bidirectional linking can't link two places, and you can't choose to jump to one of them. In addition, there is another point that onemore's Bidirectional linking can only be linked to another paragraph (such as the 'tiger' link in the figure)

# New Feature/Solution
![image](https://github.com/stevencohn/OneMore/assets/143862871/4f0f40c8-328f-4919-955a-c9477d6d4734)
1As shown in the figure, the superscript can jump to different positions
2I hope that there is one more choice for the end anchor, for example, the other two links in the picture, the cat paragraph link is cat

## Alternative Solutions

none

# Additional Context
![image](https://github.com/stevencohn/OneMore/assets/143862871/3a669663-4dd3-4ffc-9656-c23baac4d1b9)

By the way, often Bidirectional linking errors, is the superscript not able to be used as a starting anchor? The superscript link in the diagram is actually a bit wrong, the superscript first needs to be on a single line to execute the Bidirectional linking correctly, I first linked, and then deleted the line, but then the connection can't come back
![image](https://github.com/stevencohn/OneMore/assets/143862871/467d69ee-e9aa-452c-93bf-39bac06a918f)
Not only that, for example, the other one in the diagram cannot execute the Bidirectional linking command, it is just a random number of characters

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment] 2024-07-20 19:49
Closing this as a duplicate of #1427.

Note that OneNote itself does not allow a hyperlink in a paragraph to other text in that same paragraph. That is a limitation of OneNote, not OneMore.

**Closed by stevencohn** 2024-07-20 19:49 UTC
Labels: duplicate
