### ISSUE TITLE
Delay in Favourites window appearing,

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#911] opened 2023-02-15 12:06 UTC
# How can I help you?

5.7.1 Just installed.  I have 13 favourites.  From pressing alt+F, it takes 2 - 3 seconds for the dialogue to appear.   Is this the same for everyone?
It feels a bit sluggish as it is my goto command and use it once every minute, literally.  

I am not complaining, just wondering.  if it is form creation overhead, reading the file, ..... something else completely, could it be pre-created or cached?

In me IDE I press ctrl space to bring up some insight and start typing immediately.  In ON with Favourites, I press Alt+F and pause for a second, then start typing and my fingers beat the GUI and the text appears in the host page, not the Fav's search.

As always, thanks for an Amazing add-in.  I think I would consider dropping ON without it :-).

![image](https://user-images.githubusercontent.com/68282090/219019125-e4e7ea08-5d88-4ba2-aab6-164a4f76f0fd.png)

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment] 2023-02-15 12:13
So this could be caused by your _old_ favorites, those created prior to 5.7.0. These do not have the notebookID/pageID attributes so the validation logic will use the screentip attribute (used to store the named-path of the page, to lookup the page to determine if it exists. This could be exacerbated by the size of your notebooks.

If you delete/recreate those favorites, I'd be interested in seeing how long it takes to load that form.

**Comment by stevencohn** [comment] 2023-02-15 12:21
The validation logic could result in a view that looks like this:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/9964757/219025815-1bdbc503-894a-42df-a225-901e4a24725e.png">

Yellow items are the old format without the ID values, that can't be found, and have an appropriate tooltip.
Red items are the new format with the IDs, that can't be found, and you can see the tooltip here.

**Comment by jasonjac2** [comment] 2023-02-15 12:27
renamed Fav...xml, re-opened ON.  almost instant.
Adding the fav's back in.  Thanks for the quick turn around.
Ah- I wondered about the yellow. That makes sense. 
.... so what do I have to do to get the "pane" view that Gem does implemented. :-)

**Comment by stevencohn** [comment] 2023-02-15 12:30
#793 is definitely on my mind!

**Comment by jasonjac2** [comment] 2023-02-15 12:38
Just added the 16 fav's (added a couple more) and it is 1.5 - 2 , so it looks like verifying them is actually a significant cost.  Is it necessary to do that up front.  If you base the good to bad link at 20:1 and you use the dialogue once every 3 mins, then:
- cache the dialogue - then you only pay once.
- Don't check till you click - then mark it in the .xml as "possibly broken"
- if old style, then only to the re-referencing bit of code when they click it.
I could see me adding maybe 50 favs in total now you have the incremental search.

**Comment by stevencohn** [comment] 2023-02-15 12:42
could you please run the File/Analyze Data Storage command and let me know how many notebooks, pages per, and the overall size of each?

**Comment by jasonjac2** [comment] 2023-02-15 12:51
17 notebooks with about 50 - 75 sections in total.
I think about 5K pages spread over all of them.
What does: 
![image](https://user-images.githubusercontent.com/68282090/219032096-60cd20de-665f-40fb-9cd1-f91cbe5442fd.png)
mean?
If you want I can find out more precise numbers.

**Comment by stevencohn** [comment] 2023-02-15 12:57
That's a local notebook, where as the cloud icon means it's on OneDrive

**Comment by stevencohn** [comment] 2023-02-15 12:58
> If you want I can find out more precise numbers.

Nope. This will do. I can try to duplicate it with this info

**Comment by jasonjac2** [comment] 2023-02-15 14:19
That is interesting about the "local".  I thought I had set it up as the same as the others.  So that implies that it isn't being backed up.  That's not great.
Is it easy (for your tool) to distinguish between OD for business / Sharepoint / OD Personal (I am not sure if there is a difference between OD for business & Sharepoint.

**Comment by stevencohn** [comment] 2023-02-15 18:50
OneMore simply relies on how it can scan OneNote notebooks. Each notebook has a path that is either a local path (e.g. C:\...) or a remote path (e.g. onenote://...) Those two icons are driven by just that.

Personal vs. Business OD, as I understand it, is governed by current Office user, shown in the upper right of each Office app, including OneNote. So if you're logging into OneNote as a personal user, do you have access to your business notebooks and vice versa? I haven't played with it that much.

**Comment by stevencohn** [comment] 2023-02-16 01:28
Deferred validation, moving it to an explicit drop-down menu, along with a Manage Favorites option

<img width="391" alt="image" src="https://user-images.githubusercontent.com/9964757/219239144-8d36b46f-f548-4039-8c17-a65254fa8394.png">

**Comment by jasonjac2** [comment] 2023-02-16 09:21
@stevencohn  "Personal vs. Business OD, as I understand it, is governed by current Office user," - I know I started off with personal and then have a linked account to my company account.  So I have both types.  It would be good to have that info + the page count :-).

I look forward to the next release.

**Closed** 2023-02-19 00:24 UTC
Labels: bug, released
