### ISSUE TITLE
The callback function "GetRibbonLabel" was not found

### ISSUE THREAD

**Issue by tonotrain** [stevencohn/OneMore#1141] opened 2023-10-16 04:36 UTC
# Problem to Solve

Error message comes up when I open a second Onenote window

# To Reproduce

Open a second Onenote window.

# Screenshots

Error message pops up that says:

Custom UI runtime Error in OneMoreAddIn
The callback function "GetRibbonLabel" was not found

After I dismiss the errors, on the Ribbon, the OneMore icons are not fully loaded.

However, things seem to work still.

# Environment (if applicable)

 - OneNote Version: [64bit O365]
 - OneMore Version [latest]

# Additional Context

![OneMore Bug](https://github.com/stevencohn/OneMore/assets/95675147/8ea9c154-f8ed-4570-8703-0665d2185d29)

**Comment by jasonjac2** [comment] 2023-10-16 09:14
Known issue. Can't remember the # for it.  Use Ctrl+M whilst on the first instance to open a second window.

**Comment by stevencohn** [comment] 2023-10-16 10:39
Duplicate of #1058

**Closed by stevencohn** 2023-10-16 10:39 UTC
Labels: bug, duplicate
