### ISSUE TITLE
Setting Heading Style to Arial 

### ISSUE THREAD

**Issue by monoaminergic** [stevencohn/OneMore#1329] opened 2024-03-22 07:59 UTC
When creating a style in the My Style menu, if the "Style Type" is set to "Heading - include in TOC" and the font is set to Arial, the stylised text it produces will instead be in Calibri. Love the add-in by the way!

**Comment by stevencohn** [comment] 2024-03-30 10:14
Duplicate of newer #1334, which has more detail

**Closed** 2024-03-30 10:14 UTC
Labels: bug, duplicate
