### ISSUE TITLE
OneMore does not present in ribbon even if started

### ISSUE THREAD

**Issue by gianpalm** [stevencohn/OneMore#1218] opened 2023-12-17 16:40 UTC
# Problem to Solve

After installing OneMore (5.8.4 to 6.0.0) it does not show in the OneNote Ribbon
DLLHOST is properly running in Task Manager
COM Add-ins shows OneMoreAddIn present
Uninstalled and reinstalled several times on this PC without success
On other PCs with similar setup all works fine at first try

# To Reproduce

1. Install OneMore 64bit
2. open OneNote and look for the OneMore ribbon icons but the are missing
3. No alarms during install phase making it look as all worked fine

# Expected Behavior

It is expected to see OneMor in the Ribbon of OneNote.
All other PCs where I have OneMore installed it appears instantly after installation in the OneNote ribbon (without needing any configuration)

# Screenshots

None

# Environment (if applicable)

 - OneMore Version: tested several versions from 5.8.4 to the latest 6.0.0 all 64bit (tested unsuccessfully also a 32 bit version)
 - OneNote Version : Office Professional Plus 2019 - OneNote 2311 Build 17029.20068 Click-to-run

# Additional Context

Provided in the ZIP file:
- OneMore.log
- Settings directory (OLD for a saved version, before reinstalling it, and the one from the latest install)
- Running OneMore again to "Repair" the installation I get an error message attached here

Oner last comment: I have tried to run also the IQ.PS1 but my system does not allow me to run it (even after setting ExecutionPolicy). Sorry

Link to ZIP file (valid 30 days from now): https://privatebin.net/?da2dbcd30fcf9d77#4jFkNunRcuw9LFqiYhQ6K8x3DawYoJaBaM1uoYmywpBc

Thanks 
Gian

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by emuell1696** [comment] 2023-12-17 16:45
I had the same issue at one of my two clients, but after I did remove the old version using Windows uninstaller and then fresh installing the 64bit msi the Menu Items did show up again.

**Comment by gianpalm** [comment] 2023-12-17 16:55
@emuell1696 Thanks. I have uninstalled and reinstalled both OneMore (different versions) several times (probably more than a dozen) and OneNote too as I have only one machine where there is a problem (of my several PCs where this is installed). It drives me mad as I cannot understand what's the difference between all other installations successfully working and this one showing the issue. Thanks anyway for your reply.

**Comment by stevencohn** [comment] 2023-12-17 17:21
This one has eluded me for quite some time as it seems to come and go and only affects a handful of users. Please enable advanced installer logging as mentioned here https://onemoreaddin.com/get-started/Troubleshooting.htm and collect and attach that file along with %temp%\onemore.log and %temp%\onemoresetup.log. Thanks and sorry for the inconvenience..

**Comment by gianpalm** [comment] 2023-12-17 17:36
@stevencohn Hi Steven,
thanks a lot for coming back to me to look into this issue.
Please find hereafter the link to get the files you requested.
Hope it won't be too much of an issue for you to find the root cause.

Thanks again
Best
Gian

ZIP File: https://privatebin.net/?02dd283bc3757030#GMA3iYiGsSWDWjB9DSQAf2YiaMCDUb44qD3Z3EN5RP9c

**Comment by gianpalm** [comment] 2023-12-17 17:49
@stevencohn To carify the operations done after enabling the extended logging:
- uninstalled OneMore 6.0.0
- opened OneNote and closed it shortly after
- installed OneMore 6.0.0 64bit
- opened OneNote to check if the icons were present (but were not) and closed it shortly after

Thanks
Gian

**Comment by akadormouse** [comment] 2023-12-17 19:29
I had same issue after going through the update mechanism
After various starts and restarts, I downloaded the new version from scratch. When I ran it, it asked if I wanted to repair or install; I chose repair and it has worked since.

**Comment by stevencohn** [comment] 2024-01-15 18:48
Likely duplicate of #1153 and #1242

**Closed** 2024-01-15 18:48 UTC
Labels: bug, duplicate, install

**Comment by gianpalm** [comment] 2024-01-15 20:27
@stevencohn 
Thank you! 6.0.1 resolved my issue.
Thanks!
Gian

Il
15.01.2024 19:48 Steven ha scritto: 

> Likely duplicate of #1153 [1]
and #1242 [2] 
> 
> --
> Reply to this email directly, view it on GitHub
[3], or unsubscribe [4].
> You are receiving this because you authored
the thread.Message ID: @github.com>

**Comment by akadormouse** [comment] 2024-01-15 21:36
Update 6.00>6.0.1 failed with message about installer missing a program.
Modify didn't work this time.
I then uninstalled OneMore and tried installing a newly downloaded Setupx64.msi. That worked

**Comment by gianpalm** [comment] 2024-01-16 07:51
@stevencohn
Sorry, I know you closed this but I found the same issue again. 
Installed new 6.0.1 -> no ribbon icons -> uninstalled it and reinstalled it (latest build) but still with no success: still no OneMore icons on the ribbon.
If you require me to provide extra info, just let me know.
Thanks in any case.

**Comment by stevencohn** [comment] 2024-01-16 11:45
It was closed as a duplicate so the investigation is still underway. My best guess is that it is due to a configuration problem with OneNote so I've added more checks to the installer. These checks will be available in the next release, likely 6.1.0. The changes were made in the context of https://github.com/stevencohn/OneMore/issues/1153 and https://github.com/stevencohn/OneMore/issues/1242

**Comment by gianpalm** [comment] 2024-02-14 22:15
@stevencohn Hi, sorry if I post again here but after installing 6.1.0 I still do not see the ribbon in my one of my OneNotes. I collected the logs:
https://privatebin.net/?cbb02e24325c7b14#6Pe6RoCyt57HnZHSmnc1jmxLL66Vt4Y4N3sXNzEYqV67

**Comment by stevencohn** [comment] 2024-02-14 23:04
Hi @gianpalm. Sorry it's not working for you. The good news is that the installation log indicates that this may be fixed by reinstalling OneNote, or at least try rerunning the installer and choosing the Repair option.

<img width="803" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/51fe0be8-e4e8-4c01-9044-87a27ed5a8d3">
