### ISSUE TITLE
Installation error occurs with OneMore 5.0 and above versions.

### ISSUE THREAD

**Issue by zhongguocn** [stevencohn/OneMore#1075] opened 2023-07-25 08:15 UTC
System：windows 10
Onemore: 5.0 and above
Installation error message：Unable to create new stack protection pages.

installation program exits, unable to install successfully.

**Comment by stevencohn** [comment] 2023-07-25 10:23
Can you provide any more information? Are you running as an administrator on your machine? Any other contextual information you can provide?

Otherwise I have to mark this as a duplicate of #941.

**Comment by zhongguocn** [comment] 2023-07-30 14:56
> Can you provide any more information? Are you running as an administrator on your machine? Any other contextual information you can provide?
> 
> Otherwise I have to mark this as a duplicate of #941.

I speculate that it is because the installed Windows 10 system is an optimized and trimmed version, not the official complete version. May I ask what patches need to be installed to resolve this issue? Thank you.

**Comment by stevencohn** [comment] 2023-07-30 15:53
In general, I always try to keep current with the latest patches for Windows and Office.

But did you see this #941? Basically, it suggest running the msi using Windows Compatibility mode. Give that a try and let me know.

**Comment by zhongguocn** [comment] 2023-07-31 01:54
> In general, I always try to keep current with the latest patches for Windows and Office.
> 
> But did you see this #941? Basically, it suggests running the msi using Windows Compatibility mode. Give that a try and let me know.

I tried the method you suggested, but it didn't solve the problem. The installation still failed.

**Comment by stevencohn** [comment] 2023-07-31 02:26
Sorry that didn't work. If you can, more information about your configuration may help so I can see if I can reproduce your particular issue.

**Closed** 2023-11-20 10:53 UTC
Labels: duplicate
