### ISSUE TITLE
Refresh button in TOC giving error

### ISSUE THREAD

**Issue by kumar007git** [stevencohn/OneMore#1035] opened 2023-05-18 22:51 UTC
When the 'Refresh' option in Table of Contents is clicked OneNote says 'Unexpected error has occurred"

# To Reproduce
Insert Table of Contents
Click on Refresh

1. Add some headings on a page
2. Add Table of Contents
3. Click on Refresh link

# Expected Behavior
Should refresh the Table of Contents without any error

# Screenshots

# Environment (if applicable)

 - OneNote Version: Office 365, 64bit
 - OneMore Version 5.8.4

Thank you!

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment] 2023-05-25 17:44
Cannot reproduce. Can you please provide any more details?

**Comment by stevencohn** [comment] 2023-07-22 10:58
Closing. Cannot proceed without further information

**Closed by stevencohn** 2023-07-22 10:58 UTC
Labels: bug, no-repro
