### ISSUE TITLE
There is a problem with the installer package.

### ISSUE THREAD

**Issue by munish259272** [stevencohn/OneMore#539] opened 2022-07-10 14:18 UTC
**Describe the bug**
Cannot install, see the screenshot of the error

**Screenshots**
![image](https://user-images.githubusercontent.com/834673/178148428-e828f628-e98c-402d-b4da-c4f79b966e05.png)

**Environment (if applicable):**
 - OneNote Version: [O365 64bit)
 - OS : Windows 10 pro  64 bit (21H2)

**Comment by stevencohn** [comment] 2022-08-24 21:15
Duplicate of #545

**Closed by stevencohn** 2022-08-24 21:15 UTC
Labels: bug, duplicate, install
