### ISSUE TITLE
Extreme slowness formatting text when using Onenote with many pages of data

### ISSUE THREAD

**Issue by cyberlunacy** [stevencohn/OneMore#1077] opened 2023-07-27 12:57 UTC
# Problem to Solve
Extreme slowness when formatting any amount of text using OneNote with many pages of text
I don't have an idea of how many pages in a one note doc triggers this but I work daily with one that is around 40 pages of notes and code snippets and many taps of different notes.
When using Alt+C or the colorize menu option, then selecting SQL it takes upwards of 1 minute to process, even a small amount of text.
Something like this is one example of what I want to format.

update [tablename]
set [fieldname]='abc123'
where [fieldname]='xyz987'
(obviously this is small but no matter the size of what i am highlighting the result is the same)

To ask it to highlight that takes a long time, upwards of 1 minute, then it also highlights most of the rest of the doc text in a lime green color and i have to use ctrl+z to undo it.  That is an actual text highlight, not font colorization.

open a new note and paste a simple line of code like mentioned above and it is near instantly formatted.

# To Reproduce

1. Open a one note doc that is many pages long (or copy some text and paste until you have 10, 20, 30, 40 pages of text.
2. Highlight any amount of text even a few characters
3. Click Alt+C or use the Colorize menu options
4. Choose SQL
5. Wait for it to finish.
6. The OneNote app becomes unusable in this period and even goes to a completely white page note showing any text.

# Expected Behavior

When highlighting text to format, one would expect the formatting to only handle what is highlighted, not taking 1 minute or more to process given the amount of text in the Note.
The way the screen goes completely white and flashes ones or twice i almost appears that its scanning the entire Note, not just what you have highlighted.
Another app i have tested does the same thing so could be inherent to one note ?

# Screenshots

My screens would divulge possibly sensitive data publicly so I could provide a screen recording privately if this is not a known issue

# Environment (if applicable)

 - OneNote Version: Microsoft® OneNote® for Microsoft 365 MSO (Version 2306 Build 16.0.16529.20164) 64-bit 
 - Windows 11 Pro 22H2 22621.1992
 - Windows 10 Pro 22H2 19045.3208

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment] 2023-07-27 15:19
This is a known issue. Duplicate of #739.

The problem is within the Interop API of OneNote. Read the page is quick, OneMore modifying the page is quick, Writing the page back is extremely slow. I've opened a ticket with Microsoft support.

**Closed by stevencohn** 2023-07-27 15:19 UTC
Labels: bug, unread

**Comment by jasonjac2** [comment] 2023-07-27 15:23
Hi @stevencohn  when you open a ticket, are these on the forums or a private ticket?   Have you heard anything back about the issue with author changes on the page when you update a page?

**Comment by stevencohn** [comment] 2023-07-27 15:26
It should be public: https://learn.microsoft.com/en-us/answers/questions/1119987/onenote-interop-api-updatepagecontent-changes-last

and looks to be still open, possibly unread?! Not much I can do but wait I'm afraid.

**Comment by jasonjac2** [comment] 2023-08-02 10:03
Everyone, can you jump on that ticket above and add a comment to get some traction from MS?

@stevencohn for the slow writing one, have you got a ticket or a favourite ticket on that?

Do you have any other tickets or know of any that could do with some love to get visibility, ones you know someone else has raised that are stumbling blocks for you and OneMore?
