### ISSUE TITLE
Does onemore support cell merging?

### ISSUE THREAD

**Issue by yslhzj** [stevencohn/OneMore#685] opened 2022-10-21 04:17 UTC
Does onemore support cell merging?
As shown in the following figure
![image](https://user-images.githubusercontent.com/29890756/197110747-557f214c-2c28-49df-bf9c-cce7f7a820b8.png)

**Comment by stevencohn** [comment] 2022-10-21 10:22
No because this is a limitation of OneNote. Many people have submitted feature requests directly to Microsoft regarding this.

**Comment by stevencohn** [comment] 2022-10-21 10:22
Duplicate of #671

**Closed** 2022-11-08 19:00 UTC
Labels: duplicate, question, answered
