### ISSUE TITLE
Problem to Solve: import multiple files

### ISSUE THREAD

**Issue by gikillu** [stevencohn/OneMore#1353] opened 2024-04-23 09:25 UTC
For [File commands](https://onemoreaddin.com/commands/File%20Commands.htm)
Function: Import MSWord, PowerPoint, Markdown and others into the current page or a new page

I found it that it can only import single file (like *.md) at one time well, but it can not import multiple files at the same time.
Could you consider adding a function about that in the future?

**Comment by stevencohn** [comment] 2024-04-23 10:52
Duplicate of #1278

**Closed by stevencohn** 2024-04-23 10:52 UTC
Labels: duplicate
