### ISSUE TITLE
Error occured when I tried to use ConvertoMarkdown

### ISSUE THREAD

**Issue by tnncool** [stevencohn/OneMore#1429] opened 2024-06-10 05:24 UTC
# Problem to Solve

Error occured when I tried to use ConvertoMarkdown

# To Reproduce

1. Enter any note page
2. Select markdown text
3. Click 'Convert to Markdown'

# Expected Behavior

Turn text into markdown style

# Screenshots

![text waiting to be converted](https://github.com/stevencohn/OneMore/assets/82752344/32e6ecfc-9ea6-45ae-a4c1-e5c3642097f1)
![error occur](https://github.com/stevencohn/OneMore/assets/82752344/e50ca444-1dff-4384-b853-7854dfecce2b)

# Environment (if applicable)

 - OneNote Version: Office LTSC Professional Plus 2021，Windows10，64bit
 - OneMore Version: 6.4.0

# Additional Context

01|10:44:35.088| Starting dllhost 24388, 2100 Mhz, 32 MB, zh-CN/zh-CN, v6.4.0, OneNote 15.0, Office 16.0, 2024-06-08 22:44
01|10:44:35.088| ..Windows 10 Pro, Version 22H2, Build 19041, 64 bit
01|10:44:35.093| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.14332.20706)
01|10:44:35.098| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01|10:44:35.098| ..OneAddInsUpdate(custom[])
01|10:44:36.177| ..building ribbon
01|10:44:36.182| ..building ribbon colorizer commands
01|10:44:36.344| ..building ribbon language proofing commands
01|10:44:36.404| ..OnStartupComplete(custom[])
01|10:44:36.406| ..starting command service
01|10:44:36.406| ..starting reminder service
01|10:44:36.407| ..starting navigation service
01|10:44:36.409| ..starting hashtag service, PendingRebuild
01|10:44:36.409| ..ready
09|10:44:36.495| starting C:\Program Files\River\OneMoreAddIn\OneMoreTray.exe @2024-06-08T16:00:00.0000Z
03|10:44:36.590| defined 51 hotkeys for input locale 2052
09|10:44:36.607| started OneMoreTray process 24068
……
04 | 07:29:22.679 | Running command ConvertMarkdownCommand
16 | 07:29:22.703 | Error running command ConvertMarkdownCommand
16 | 07:29:22.703 | System TypeLoadException
Message: Could not load type 'System. Numerics. Vector ` 1' from assembly 'System. Numerics. Vectors, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Source: System.Memory
StackTrace:     In System SpanHelpers. IndexOf (Char&searchSpace, Char value, Int32 length)
At Markdig Parsers. FencedBlockParserBase ` 1. Default InfoParser (BlockProcessor state, StringSlice& line, IFencedBlock fenced, Char openingCharacter)
At Markdig Parsers. FencedBlockParserBase ` 1. TryOpen (BlockProcessor processor)
At Markdig Parsers. BlockProcessor. TryOpenBlocks (BlockParser [] Parsers)
At Markdig Parsers. BlockProcessor. TryOpenBlocks()
At Markdig Parsers. BlockProcessor. ProcessLine (StringSlice newLine)
At Markdig Parsers. MarkdownParser. ProcessBlocks (BlockProcessor, String text)
At Markdig Parsers. MarkdownParser. Parse (String text, MarkdownPipeline pipeline, MarkdownParserContext context)
At River OneMoreAddIn. Demands. OneMoreDig. ConvertMarkdownToHtml (String path, String markdown)
At River OneMoreAddIn. Orders. ConvertMarkdownCommand.<Execute>d_1. MoveNext()
---At the end of the stack trace in the previous position that caused the exception---

**Comment by stevencohn** [comment] 2024-07-15 14:39
Duplicate of, and resolved by, #14210
Closing this ticket and releasing under 1410 instead.

**Closed by stevencohn** 2024-07-15 14:39 UTC
Labels: bug, duplicate
