### ISSUE TITLE
Resize and adjust dialog: Limit setting is lost when doing a single image

### ISSUE THREAD

**Issue by JRPX33** [stevencohn/OneMore#1061] opened 2023-07-20 02:11 UTC
In the "resize an Adjust" dialog, the Limit setting persists between usage, which is great.  However, I've found that if you run the command on a single image, or even if you run it on a page with only one image, and it slips into single image mode which doesn't have that field, then the next time you run the command on a page with multiple images, it goes to a blank Limit setting like this:

![image](https://github.com/stevencohn/OneMore/assets/123988676/410eb8f0-13ae-42b8-8730-c0519ec1a103)

Ideally it would remember the Limit setting throughout single and multiple image usage.

**Comment by stevencohn** [comment] 2023-07-22 11:59
Closing as duplicate of #1060

**Closed by stevencohn** 2023-07-22 11:59 UTC
Labels: bug, duplicate
