### ISSUE TITLE
Feature request: Export HTML with attachments 

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#153] opened 2021-01-09 15:19 UTC
Export as HTML with attachments preserved, to create a OneNote-independent backup of data

**Comment by stevencohn** [comment] 2021-01-11 22:44
Note from G2G2G2, paraphrased: export HTML with attachments, preserving links to local files so HTML page still works

**Comment by stevencohn** [comment] 2021-01-17 11:04
https://github.com/stevencohn/OneMore/releases/tag/3.14

**Comment by G2G2G** [comment] 2021-01-17 19:52
Thank you ! It works great. Thank you so much for releasing it so quickly.

What would be the best steps to follow to back up an entire notebook ?

**Comment by stevencohn** [comment] 2021-01-17 22:14
This was intended to quickly export one or a few pages and presumably share them using a common format that anyone can read. It's really not a good solution for backups since the HTML output is lossy; e.g. although OneMore can import HTML, the result will not be identical.

OneNote itself has a backup feature that you can set in the Options dialog, under Save and Backup. It let you specify a backup folder and then either schedule or manually backup your notebooks. If you're extra sensitive, you can backup the backup folder to offline storage.

**Comment by G2G2G** [comment] 2021-01-17 23:21
Sorry, I wasn’t clear enough. I was mostly thinking about a backup that is independent of Onenote. Otherwise, user’s notes are pretty much stuck in it. I make heavy use of attachments, and If tomorrow I decided, or was forced to switch away from Onenote, I’d have no way to preserve my notes in a usable shape, unless there’s an importer into whatever other service I would chose.  With html however, I have a way to retain my notes in a common, universal format, with attachments still functional, so I am not risking to be locked out of my data. If formatting is not 100% preserved, that’s no biggie.

My biggest concern was the MS’ decision to make the UWP version the only supported version, and stop supporting the desktop. If they continued along that path, then at some point the backups created in ON 2016 could become useless. This means data being locked into Onenote, and relying on MS OneDrive not ever screwing up. I know that they seem to have reverted back to supporting the desktop for now.

Eugene

On Jan 17, 2021, at 5:14 PM, Steven <notifications@github.com> wrote:

﻿

This was intended to quickly export one or a few pages and presumably share them using a common format that anyone can read. It's really not a good solution for backups since the HTML output is lossy; e.g. although OneMore can import HTML, the result will not be identical.

OneNote itself has a backup feature that you can set in the Options dialog, under Save and Backup. It let you specify a backup folder and then either schedule or manually backup your notebooks. If you're extra sensitive, you can backup the backup folder to offline storage.

**Comment by stevencohn** [comment] 2021-01-27 15:53
I have a notebook/section export in development. It exports HTML into a directory structure that mirrors the sectiongroup/section/page hierarchy under that notebook or section. The final output is actually a Zip of that hierarchy.

The one aspect that you bring up that is new and interesting is hyperlinking page-to-page references in the HTML. That should be possible. Thanks

**Comment by G2G2G** [comment] 2021-01-27 18:44
Thank you ! This would be a huge functionality improvement because it allows easy export of notebooks in a standard commonly accessible format at any time. 

BTW is there any way to donate other than Paypal ? I deleted my PP account.

**Comment by stevencohn** [comment] 2021-01-27 22:12
That's very kind of you. You could donate to a cancer charity. That would make me just as happy

**Comment by stevencohn** [comment] 2021-02-02 18:16
Notebook archive coming soon... closing this story since it wasn't originally inclusive of that enhancement

**Closed by stevencohn** 2021-02-02 18:16 UTC
Labels: enhancement, released
