### ISSUE TITLE
Style menus are blurry on high-res screens

### ISSUE THREAD

**Issue by sstoilovABLE** [stevencohn/OneMore#783] opened 2022-12-03 13:04 UTC
**Describe the bug**
On my machine I'm observing that the style previews within the Custom Styles and Table Styles menus of OneMore are noticeably less sharp than the rest of OneMore's menus and OneNote's built-in menus. I'm assuming that this is probably the case on high-res screens with a high pixel density. It would be great if this were improved.

**To Reproduce**
1. Install OneMore on a laptop with a high-res screen. 
2. Open OneNote and open either the Custom Styles or the Table Styles menu. 
3. Observe that the names of the styles and their previews within the upper part of the Custom Styles dropdown are blurry/low-res/less sharp compared to the rest of the OneNote menus. 

**Expected behavior**
I expect the style previews within the Custom Styles and Table Styles dropdown menus should be as sharp as the rest of the menus.

**Screenshots**
Screenshot of the Custom Styles dropdown menu of OneMore: 
![image](https://user-images.githubusercontent.com/20355843/205441707-84a47d42-4ff9-41c7-8b9b-71eebb892de6.png)

Screenshot of the Table Styles dropdown menu of OneMore: 
![image](https://user-images.githubusercontent.com/20355843/205441696-db6b744c-4b19-490c-aa33-1b5dba6cd4fe.png)

Screenshot of the OneNote built-in Styles dropdown menu: 
![image](https://user-images.githubusercontent.com/20355843/205441736-6bdd8937-6d73-47fd-ace9-c4b02866bf7a.png)

Screenshot of the Styles menu in Microsoft Word on the same machine: 
![image](https://user-images.githubusercontent.com/20355843/205442044-f5568964-51e4-4168-9354-a3d5f63f751a.png)

**Environment (if applicable):**
- Microsoft® OneNote® for Microsoft 365 MSO (Version 2210 Build 16.0.15726.20188) 64-bit 
- Machine: ASUS Zenbook 14-inch Flip OLED with a 2880x1800 resolution OLED screen. 

**Additional context**
Log data is not applicable.

**Comment by stevencohn** [comment] 2022-12-03 13:54
Marking duplicate of #687. Will address from that ticket

**Closed** 2022-12-03 15:54 UTC
Labels: bug, duplicate
