### ISSUE TITLE
Ribbon icons and/or their text are missing sometimes

### ISSUE THREAD

**Issue by dowiew** [stevencohn/OneMore#1076] opened 2023-07-26 13:04 UTC
# Problem to Solve

An old problem, but I haven't bothered to submit it for years.
When I start OneNote, the OM ribbon icons lack its icons and/or their descriptions. See the screenshot.
Today, after 5.8.5 update (from some 4.x ver) the problem is still there.

# To Reproduce
Start ON first time (rarely happens now), open a new window from Windows (always happens), open a new window with Ctrl-M (never happens), 

# Screenshots
Ribbon correct and incorrect:
![image](https://github.com/stevencohn/OneMore/assets/11893602/488c0cb8-bb92-4a4a-ada2-5177c5d38658)
![image](https://github.com/stevencohn/OneMore/assets/11893602/28957030-34fe-484d-8b0f-45ff33178b9b)

# Environment (if applicable)

Microsoft® OneNote® dla Microsoft 365 MSO (wersja 2306 kompilacji 16.0.16529.20164) 64-bitowa 
OneMore - Version 5.8.5 with OneNote 16.0.16529.20182

The log file (is not updated when I open a new window in any way):
01| Starting dllhost 20644, 3601 Mhz, 64 MB, en-US/en-US, v5.8.5, OneNote 15.0, Office 16.0, 2023-07-26 14:59
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16529.20182)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
03| defined 43 hotkeys for input locale 1045

**Comment by stevencohn** [comment] 2023-07-26 20:29
Known issue. Duplicate of #1058

**Closed by stevencohn** 2023-07-26 20:29 UTC
Labels: bug, duplicate
