### ISSUE TITLE
Search and replace is adding empty lines 

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#126] opened 2020-12-17 03:09 UTC
**Describe the bug**
for the below code I am trying to replace >>>  with nothing (eliminate)

**To Reproduce**
Paste this text in an empty window
```
>>>
Gfdg fdgdfgdfgdg
>>> idfs 
>>> idsfsdfsdf
>>> HEAdgdfdg} 
>>>dfgdfgdfgdfgfd
Dfgddfgdfgdfgfdgdfg
fdgdfgdfgdfgdfgdf
>>> sdfsdfdf
Fsdfsdfsdf
>>> gdfgdfgdfgdf

```

**Expected behavior**
use Search and replace and try to replace >>> with nothing (remove) or with an empty space
It will do it but it will add empty lines

Trying to get the XML tree to paste the code there causes this error

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at River.OneMoreAddIn.OneNote.GetPageInfo()
   at River.OneMoreAddIn.Commands.ShowXmlDialog.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
River.OneMoreAddIn
    Assembly Version: 3.10.6.0
    Win32 Version: 3.10.6
    CodeBase: file:///C:/Program%20Files%20(x86)/River/OneMoreAddIn/River.OneMoreAddIn.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Microsoft.Office.Interop.OneNote
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.5287.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.OneNote/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.OneNote.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.Office.Interop.Word
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.5293.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.Word/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Word.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.5293.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

The XML code for the above just in case you needed it
```

<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{xxxxxxx}" name="&gt;&gt;&gt;" dateTime="2020-12-17T03:00:06.000Z" lastModifiedTime="2020-12-17T03:05:50.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="yo">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="11.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="yo">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="540.0" height="147.7048645019531" />
    <one:OEChildren selected="partial">
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[&gt;&gt;&gt;]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[Gfdg fdgdfgdfgdg]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[&gt;&gt;&gt; idfs <br>
&gt;&gt;&gt; idsfsdfsdf<br>
&gt;&gt;&gt; HEAdgdfdg} ]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[&gt;&gt;&gt;dfgdfgdfgdfgfd]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[Dfgddfgdfgdfgfdgdfg]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[fdgdfgdfgdfgdfgdf]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[&gt;&gt;&gt; sdfsdfdf]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[Fsdfsdfsdf]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[&gt;&gt;&gt; gdfgdfgdfgdf]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>

```

**Comment by stevencohn** [comment] 2020-12-17 10:49
This is another one of those soft-break issues.  I'll take a look

While this project has been and is still fun, sometimes I just hate OneNote :-)

**Comment by 1001QAdotNET** [comment] 2020-12-17 12:41
Yeah tell me about it. I started my work with OneNote REST apis and Graph then I run into limitations , the I tried to learn Javascript just to be able to write a plugin for OneNote online and now I am trying to leverage your Plugin interface. I also moved from dealing with HTML to XML

**Comment by stevencohn** [comment] 2020-12-19 10:41
https://github.com/stevencohn/OneMore/releases/tag/3.10.7

Generally a rewrite of Search and Replace that fixes a multitude of defects... This was one of the first commands I wrote and clearly I've learned quite a bit since then about how OneNote wants to work.

**Comment by CLITrees** [comment] 2020-12-19 13:26
Using the content I posted initially if you try to replace >>> with nothing and you do not select anything it works
If you select everything and you use the same you see this
![search and replace failing](https://user-images.githubusercontent.com/67560397/102690505-e15ff800-41d3-11eb-9af9-b19fbe43a07a.gif)

**Comment by stevencohn** [comment] 2020-12-19 13:59
Am able to reproduce. Looking at it now. By the way, this command is bound to the keyboard shortcut Ctrl + H

**Comment by CLITrees** [comment] 2020-12-19 14:08
Will try to remember that shortcut , thank you, I am really bad at these

**Comment by 1001QAdotNET** [comment] 2020-12-19 14:10
Will try to remember that one, I am really bad at these (way too many programs that I am using) Yes that one is generally valid for most of the editors

**Comment by 1001QAdotNET** [comment] 2020-12-19 14:11
Will try to remember that one, I am really bad at these (way too many programs that I am using) Yes that one is generally valid for most of the editors

Edit: closed by mistake, need coffee

**Comment by stevencohn** [comment] 2020-12-19 16:36
Fixed, tested as many cases as I could think of.

However, this introduces an odd behavior where OneNote insert a space after a soft-break. I'm trying to work through this. There may also be a problem (not sure if it's new) with the rotating highlighter than I'm looking into...

3.10.8

**Comment by 1001QAdotNET** [comment] 2020-12-19 17:04
OK I will let you know if I run into any other bugs for this feature
Thanks a lot  for the quick fix

**Comment by 1001QAdotNET** [comment] 2020-12-19 17:05
re:colorizer..yes I think it still has bugs 
I have noticed in one occasion that it still removes a soft break and moves/joins the text with the line above it

**Comment by stevencohn** [comment] 2020-12-19 20:11
Closing this one because I think it's fixed. If there are other issues, please open new tickets

**Closed by stevencohn** 2020-12-19 20:11 UTC
Labels: bug, released
