### ISSUE TITLE
Hashtag search results in dark mode are gray on gray with a white shadow, hard to read

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#1493] opened 2024-07-22 12:18 UTC
# Problem to Solved

If the Theme is set to dark, the text in the hashtag search results is dark on dark background

**Comment by stevenmcohn** [comment] 2024-07-22 12:22
Can you please show a screen shot?

This is what it should look like:

<img width="494" alt="image" src="https://github.com/user-attachments/assets/2bf5607a-2dab-479b-ae42-663ff99df84e">

**Comment by stevencohn** [comment] 2024-07-22 12:23
Can you provide a screenshot? This is what is should look like:

<img width="494" alt="image" src="https://github.com/user-attachments/assets/f933d741-d905-4d49-9910-0fef60c367e4">

**Comment by G2G2G** [comment] 2024-07-22 12:23
For some reason it doesn't save when I try to upload. Can I email it ?

**Comment by G2G2G** [comment] 2024-07-22 12:31
![Screenshot 2024-07-22 081655](https://github.com/user-attachments/assets/7e9a07f4-20da-4a6c-a6f4-4ecf95b1ee88)

**Comment by stevencohn** [comment] 2024-07-22 12:52
Items will be disabled if OneMore things the notebook is inaccessible. Is that notebook loaded in OneNote currently?

**Comment by G2G2G** [comment] 2024-07-22 13:14
Yes. Here’s how it looks when I set the theme to light

![Screenshot 2024-07-22 091230](https://github.com/user-attachments/assets/685daf04-db53-462a-a147-c83b99976cd1)

**Comment by stevencohn** [comment] 2024-07-22 13:28
Theme shouldn't matter, it thinks the _Word References_ notebook is unloaded, so will still disable each item in that notebook. 

This was intended to show you that there are known tags in the catalog, even if you can't hyperlink to them at  the moment. A future enhancement was going to add an option to include/exclude these results.

But if the notebook is loaded - I presume you're viewing it right now? - then this is an issue in the way OneMore "sees" that notebook. Maybe the log file would help. Could you try to attach it here? Maybe as a zip.

`%temp%\OneMore.log`

**Comment by G2G2G** [comment] 2024-07-22 16:30
[OneMore.zip](https://github.com/user-attachments/files/16336971/OneMore.zip)

**Comment by stevencohn** [comment] 2024-07-22 16:40
Starting on July 17, it looks like OneNote was having trouble syncing one of your notebooks. If it's stuck during a sync, OneMore sometimes has trouble talking to OneNote; this is a limitation of OneNote itself and OneMore will retyr a few times before giving up.

Does the notebook in question appear to stuck trying to sync online?

**Comment by stevencohn** [comment] 2024-07-22 16:42
One option is that you can force OneNote to rebuild the hashtag catalog. You can do this by closing OneNote, and then deleting the file

`%appdata%\OneMore\OneMore.db`

When you restart OneNote, it will want to rebuild the hashtag catalog which could take a couple of minutes. You only have somewhere around 1500 page total so it shoudn't take long

**Comment by G2G2G** [comment] 2024-07-22 16:45
OK thanks

**Comment by stevencohn** [comment] 2024-07-27 01:54
Is it working for you now? Can this be closed?

**Comment by stevencohn** [comment] 2024-10-15 14:16
closing due to inactivity

**Closed by stevencohn** 2024-10-15 14:16 UTC
Labels: bug
