### ISSUE TITLE
Automatic Backlinks

### ISSUE THREAD

**Issue by KlausSGS** [stevencohn/OneMore#772] opened 2022-11-30 11:02 UTC
**Is your feature request related to a problem? Please describe.**
In general OneNote is organized strictly hierachical. A page that belongs to different subjects needs to exist in exactly one place.
Modern note taking systems like Obsidian, LogSeq, Roam, etc. heavily rely on linking and tagging.
OneNote is able to link pages but the links are missing the backlinks. The page to be targeted by a link does not reflect that - we can't see this relation.
This problem has already been addressed by the "Link references to this page" function in OneMore that allows to find references and adds the backlinks to the bottom of the page.
Unfortunately this requires to explicitly run the command for every single page and also needs to be updated manually to reflect changes.

**Describe the solution you'd like**
Allow to add / update backlinks **automatically** whenever a link is created or updated.
This might be optional, maybe switched on or off globally or per notebook or section.
Triggering the creation of the backlink directly when a link is created would be perfect.
If this is not possible, running the update of backlinks for all links on schedule in the background or at least updating **all** pages on demand would still help.

**Describe alternatives you've considered**
Manually creating / updating the backlink every time a link is created might work but seems tedious and error prone.

**Additional context**
I would really like to be able to use OneNote in a similar way as Logseq, Obsidian, etc.
Having a rather flat hierarchy with notebooks, section groups, sections, pages plus a smoothly working way of accessing information using tags and links would allow for a completely different approach in OneNote. Best of both worlds :)

**Comment by KlausSGS** [comment] 2022-12-02 10:08
Oops,  I just found that "Link references to this page" does not only put backlinks on a page but also creates new links on all strings that are identical to the page title. So this is a completely different story.

**Comment by KlausSGS** [comment] 2022-12-02 10:22
@stevencohn Could you please give a short overview on where you are heading with OneMore? That might be interesting for others, too. So maybe you could add some kind of "future development", vision statement, road map or the like to the wiki?
I would love to see OneMore providing features like Obsidian, Roam, LogSeq etc.
That would allow to use OneNote in a completely different - modern? - way. I guess that would be interesting for quite some people.
Is that something that sounds interesting to you?

**Comment by stevencohn** [comment] 2022-12-02 12:55
So this has been brought up a couple of times from a couple of different angles but the root of the problem is that OneNote has its own philosophy and meaning in life which differs fundamentally from the likes of Obsidian, Roam, LogSeq, etc. OneNote generally likes structure, whereas other tools approach the problem as a big "mind map". Neither is more correct than the other. I believe it comes down to your personality. Personally, I find comfort in the more structured approach and never found joy in trying to construct a mind map of ideas. Whereas I know others find the more fluid and dynamic approach works better for them.

OK, so all of that to say that OneMore isn't trying to make OneNote something that it isn't. Regardless, Microsoft hasn't provided the APIs necessary to create the types of plugins that would enable such an evolution. For example, there is almost no "eventing mechanism" within the API that would allow a plugin to act in real-time. (The OneMark plugin uses polling and screen-scraping which IMHO is inaccurate and a performance drain - no disrespect to that project, it's fine work) Also there is no access to the side panels or the ability to create custom panels. The content is limited to a well-defined XML schema that prevents things that one might consider basic like merging table cells.

OneMore tries to fill gaps that I and other users have found in an attempt to make OneNote a better OneNote.

There hasn't been a road map, per se. It's been evolving virally, with welcomed input from awesome users. And while I make no promises as to where it will go, I have always and will continue to the best of my ability, for as long as I can, support feature requests that fit the mission.

To give you small peek behind the curtain though, a couple of things that are on my mind... Would it be possible to build a better, faster, more accurate and powerful search and replace tool? Also, what is tagging and what would make 80% of users happy/happier?

**Comment by KlausSGS** [comment] 2022-12-02 13:04
OK, so my wishes won't come true this christmas :(
Anyway, thanks a lot for your time and effert to provide such a feature rich tool!

**Comment by stevencohn** [comment] 2023-03-22 06:27
I think this is satisfied by the "Link References to Page" and "Bi-Directional Linking" features on OneMore. I believe both of these could be improved. But for now, I'm closing this ticket and may address these improvements elsewhere.

**Closed by stevencohn** 2023-03-22 06:27 UTC
Labels: feature-request
