### ISSUE TITLE
Page search function

### ISSUE THREAD

**Issue by sezhai** [stevencohn/OneMore#1676] opened 2024-11-19 04:39 UTC
OneNote's text search function has very poor support for Chinese. You have built so many functions, why don't you just build a simple search function? Not a find and replace, nor a find tag.

**Comment by stevencohn** [comment] 2024-11-19 15:08
Duplicate of #1084 and #561, #971, #972, #1121, #1136, #1279

**Closed** 2024-11-19 15:08 UTC
Labels: duplicate
