### ISSUE TITLE
The Onemore plugin is causing severe lag in OneNote.

### ISSUE THREAD

**Issue by 593388896** [stevencohn/OneMore#1555] opened 2024-08-22 04:35 UTC
![image](https://github.com/user-attachments/assets/45111612-0967-464a-967a-3b5adefce095)

I have a total of four plugins, including Onemore. I noticed that after disabling each one, the issue seems to occur specifically when Onemore is enabled—OneNote becomes extremely slow and almost unresponsive. I'm not sure if it's a bug, but I'm using the latest version of OneNote. When you have time, could you help me check if this is a problem on my end or if it's a common issue?

**Comment by stevencohn** [comment] 2024-08-22 06:59
Likely duplicate of #1506 
To be part of next release

**Closed** 2024-10-15 14:26 UTC
Labels: bug, duplicate
