### ISSUE TITLE
Update to OneMore v5 on OneNote 2209 causes OneMore not to appear in UI 

### ISSUE THREAD

**Issue by tridian-tn** [stevencohn/OneMore#622] opened 2022-09-21 08:51 UTC
**Describe the bug**
I had OneMore 4.17 x64 installed. I upgraded OneNote to the latest 2209 x64. OneMore was accessible via the ribbon and context menu.

I then upgraded OneMore to v5, using the msi (the auto update appeared to work (OneNote closed automatically), but the OneMore version was unchanged when OneNote was relaunched).

When relaunching OneNote, OneMore was missing from the UI. The addin was still enabled in the COM addins window, but there was no ribbon (either visible, or in the ribbon customisation UI), and the OneMore context menu entries were missing. In effect, the addin was disabled....without having been disabled.

**To Reproduce**
1. Have OneNote 2209 installed with OneMore 4.17
2. Close OneNote. Install the OneMore 5 update
3. Open OneNote

**Expected behavior**
The ribbon and context menu UI should still be active

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: 2209 15629 64 bit, from the Office insider preview 
 - OneMore Version 5

**Additional context**
I uninstalled OneMore v5 and installed v4.19 - the ribbon and context menu were restored, so I have a workaround.

Log entries:

```

37240:1] Starting dllhost 37240, CPU=1700Mhz, en-US/en-US, v4.17, OneNote 15.0, Office 16.0
37240:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15629.20118)
37240:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
37240:1] ..OneAddInsUpdate(custom[])
37240:1] ..building ribbon
37240:1] ..building ribbon colorizer commands
37240:1] ..building ribbon language proofing commands
37240:1] ..building context menu
37240:1] ..OnStartupComplete(custom[])
37240:1] ..starting command service
37240:1] ..starting reminder service
37240:1] ..defining hotkeys for input locale 1033
37240:1] ..ready
37240:9] Running command UpdateCommand
37240:15] OnBeginShutdown(custom[])
37240:15] ..shutting down UI
37240:15] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
37240:15] ..disposing 1 streams
37240:15] ..closing log

36432:1] Starting dllhost 36432, CPU=1700Mhz, en-US/en-US, v5.0.0, OneNote 15.0, Office 16.0
36432:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15629.20118)
36432:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
36432:1] ..OneAddInsUpdate(custom[])
36432:1] ..building ribbon
36432:1] ..building ribbon colorizer commands
36432:1] ..building ribbon language proofing commands
36432:1] ..building context menu
36432:1] ..OnStartupComplete(custom[])
36432:1] ..starting command service
36432:1] ..starting reminder service
36432:1] ..defining hotkeys for input locale 1033
36432:1] ..ready
36432:9] Running command UpdateCommand
36432:1] OnBeginShutdown(custom[])
36432:1] ..shutting down UI
36432:1] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
36432:1] ..closing log

31296:1] Starting dllhost 31296, CPU=1700Mhz, en-US/en-US, v5.0.0, OneNote 15.0, Office 16.0
31296:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15629.20118)
31296:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
31296:1] ..OneAddInsUpdate(custom[])
31296:1] ..building ribbon
31296:1] ..building ribbon colorizer commands
31296:1] ..building ribbon language proofing commands
31296:1] ..building context menu
31296:1] ..OnStartupComplete(custom[])
31296:1] ..starting command service
31296:1] ..starting reminder service
31296:1] ..defining hotkeys for input locale 1033
31296:1] ..ready
31296:9] Running command UpdateCommand
31296:15] OnDisconnection(RemoveMode:ext_dm_UserClosed,custom:[])
31296:15] closing log

11116:1] Starting dllhost 11116, CPU=1700Mhz, en-US/en-US, v5.0.0, OneNote 15.0, Office 16.0
11116:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15629.20118)
11116:1] ..OnConnection(ConnectionMode:ext_cm_AfterStartup,custom[1:Int32])
11116:1] ..OneAddInsUpdate(custom[])
11116:1] ..building ribbon
11116:1] ..building ribbon colorizer commands
11116:1] ..building ribbon language proofing commands
11116:1] ..building context menu
11116:1] ..OnBeginShutdown(custom[])
11116:1] ..shutting down UI
11116:1] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
11116:1] ..closing log

41800:1] Starting dllhost 41800, CPU=1700Mhz, en-US/en-US, v5.0.0, OneNote 15.0, Office 16.0
41800:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15629.20118)
41800:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
41800:1] ..OneAddInsUpdate(custom[])
41800:1] ..building ribbon
41800:1] ..building ribbon colorizer commands
41800:1] ..building ribbon language proofing commands
41800:1] ..building context menu
41800:1] ..OnStartupComplete(custom[])
41800:1] ..starting command service
41800:1] ..starting reminder service
41800:1] ..defining hotkeys for input locale 1033
41800:1] ..ready
41800:9] Running command UpdateCommand
41800:1] OnBeginShutdown(custom[])
41800:1] ..shutting down UI
41800:1] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
41800:1] ..closing log

42656:1] Starting dllhost 42656, CPU=1700Mhz, en-US/en-US, v5.0.0, OneNote 15.0, Office 16.0
42656:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15629.20118)
42656:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
42656:1] ..OneAddInsUpdate(custom[])
42656:1] ..building ribbon
42656:1] ..building ribbon colorizer commands
42656:1] ..building ribbon language proofing commands
42656:1] ..building context menu
42656:1] ..OnStartupComplete(custom[])
42656:1] ..starting command service
42656:1] ..starting reminder service
42656:1] ..defining hotkeys for input locale 1033
42656:1] ..ready
42656:9] Running command UpdateCommand
42656:15] OnBeginShutdown(custom[])
42656:15] ..shutting down UI
42656:15] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
42656:15] ..closing log

4560:1] Starting dllhost 4560, CPU=1700Mhz, en-US/en-US, v4.19, OneNote 15.0, Office 16.0
4560:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15629.20118)
4560:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
4560:1] ..OneAddInsUpdate(custom[])
4560:1] ..building ribbon
4560:1] ..building ribbon colorizer commands
4560:1] ..building ribbon language proofing commands
4560:1] ..building context menu
4560:1] ..OnStartupComplete(custom[])
4560:1] ..starting command service
4560:1] ..starting reminder service
4560:1] ..defining hotkeys for input locale 1033
4560:1] ..ready
4560:9] Running command UpdateCommand
4560:1] Running command AboutCommand
```

**Comment by stevencohn** [comment] 2022-09-21 11:39
I suspect this is a duplicate of #612 

Please rerun the v5.0 installer and look for the log file %TEMP%\OneMoreSetup.log. You may see a couple of lines like this:

```
RegistryWowAction.Install --- x64:True
OneNote application path note found; continuing optimistically
```

(Note that the word "note" here should actually be the word "not") This would indicate that there is a problem with your OneNote installation, in which case, I recommend a reinstall or repair-install of OneNote

**Comment by tridian-tn** [comment] 2022-09-21 12:52
> I suspect this is a duplicate of #612
> 
> Please rerun the v5.0 installer and look for the log file %TEMP%\OneMoreSetup.log. You may see a couple of lines like this:
> 
> ```
> RegistryWowAction.Install --- x64:True
> OneNote application path note found; continuing optimistically
> ```
> 
> (Note that the word "note" here should actually be the word "not") This would indicate that there is a problem with your OneNote installation, in which case, I recommend a reinstall or repair-install of OneNote

Thanks. I uninstalled the addin, reinstalled Office in full and then installed the addin again - v5. The same problem occurred, and the setup log contains that line. I;ve put 4.19 back on and that works fine.

I've attached the log with the various installs and uninstalls, in case it's helpful.
[OneMoreSetup.log](https://github.com/stevencohn/OneMore/files/9616694/OneMoreSetup.log)

**Comment by stevencohn** [comment] 2022-09-21 12:58
Thanks for trying. 

That "application path not found" line is because it's looking for the Windows Registry key `HKEY_CLASSES_ROOT\OneNote.Application` which should always exist and is the root key use by interop addons like OneMore.

So it's a bit baffling because OneMore shouldn't work at all, regardless of version, due to this missing Registry entry! I'm not even sure how that key can go missing. I'll keep researching...

**Comment by tridian-tn** [comment] 2022-09-21 13:01
It's supposedly there. Is there a permissions problem maybe? Something came up on the setup log when trying to delete a key.

![image](https://user-images.githubusercontent.com/10810780/191510347-2f126d67-af4c-4631-84f8-87b2b3698c23.png)

I'm happy to run a debug build of the setup if that'll help

**Comment by stevencohn** [comment] 2022-09-21 13:17
I just realized this is an Office Insider Preview version of OneNote. I know others have had issues with beta/preview versions. Unfortunately, I don't have access to those builds. I'll see if I can get access but there's clearly something odd about those installations. More digging...

**Comment by stevencohn** [comment] 2022-09-22 15:24
I've uploaded an experimental install here https://github.com/stevencohn/OneMore/releases/tag/5.0.1-EXPERIMENTAL

If you have a chance, I'd appreciate it if you could try it out.

I haven't been able to repro the problem exactly but I have at least one machine that exhibits a problem reading the registry key causing the "application path not found" message in the log file. This attempt to circumvent that.

Thanks!

**Comment by tridian-tn** [comment] 2022-09-22 15:28
@stevencohn thanks! I installed the 5.0.1 setup: same results as before (no ribbon entries in OneNote). OneMoreSetup.log chunk as follows:

```
======================================================================
starting action: --install
Installer architecture (x64), OS architecture (x64), requesting (x64)
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

Register... version 5.0.1

ShutdownOneNoteAction.Install ---
ONENOTE process not found

ProtocolHandlerAction.Install ---
step 0: opening HKLM:\Software\Classes\onemore
step 1: setting properties of HKLM:\Software\Classes\onemore
step 2: opening HKLM:\Software\Classes\onemore\shell\open\command
step 3: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command

TrustedProtocolAction.Install ---
translating user LAPTOP-313I67C4\trystan negus to SID
registering trusted protocol for user LAPTOP-313I67C4\trystan negus (S-1-5-21-40216402-3561120254-1172930677-1002)
defaulting Office version to 16
step 4: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
key already exists

EdgeWebViewAction.Install ---
WebView2 Runtime is already installed
install completed successfully

--------------------------------------------------
reentry action: --install-registrywow
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

RegistryWowAction.Install --- x64:True
1st chance, could not read CLSID or key missing
2nd chance, read CLSID ({DC67E480-C3CB-49F8-8232-60B0C2056C8E})
read path from LocalServer32 ()
read path from WOW6432Node\..\LocalServer32 (C:\Program Files (x86)\Microsoft Office\Root\Office16\ONENOTE.EXE)
detected 32-bit install
step 0: deleting CLSID clone
step 1: cloning CLSID
step 2: copying from HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61} to HKEY_CLASSES_ROOT\WOW6432Node\CLSID
created clone HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}
clone property  = River.OneMoreAddIn.AddIn (String)
clone property AppID = {88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61} (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Implemented Categories
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Implemented Categories\{62C8FE65-4EBB-45E7-B440-6E39B2CDBF29}
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32
clone property  = mscoree.dll (String)
clone property ThreadingModel = Both (String)
clone property Class = River.OneMoreAddIn.AddIn (String)
clone property CodeBase = C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll (String)
clone property Assembly = River.OneMoreAddIn, Version=5.0.1.0, Culture=neutral, PublicKeyToken=null (String)
clone property RuntimeVersion = v4.0.30319 (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32\4.19.0.0
clone property Class = River.OneMoreAddIn.AddIn (String)
clone property RuntimeVersion = v4.0.30319 (String)
clone property CodeBase = C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll (String)
clone property Assembly = River.OneMoreAddIn, Version=4.19.0.0, Culture=neutral, PublicKeyToken=null (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32\5.0.1.0
clone property RuntimeVersion = v4.0.30319 (String)
clone property Class = River.OneMoreAddIn.AddIn (String)
clone property CodeBase = C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll (String)
clone property Assembly = River.OneMoreAddIn, Version=5.0.1.0, Culture=neutral, PublicKeyToken=null (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\ProgID
clone property  = River.OneMoreAddin (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Programmable
clone property  =  (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\TypeLib
clone property  = {88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61} (String)
created subkey HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\VersionIndependentProgID
clone property  = River.OneMoreAddIn (String)

--------------------------------------------------
reentry action: --install-activesetup
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

ActiveSetupAction.Install ---
replacing '5.0.1' with '5,0,1'

```

**Comment by tridian-tn** [comment] 2022-09-22 15:30
@stevencohn ah. I'v spotted the 32bit vs 64bit conflict here. Bear with me - the reinstall of Office was giving me all the signs that it was installing a 32bit version. One sec.....

**Comment by stevencohn** [comment] 2022-09-22 15:32
The installer should abort pretty quickly if you're using the wrong bit version

**Comment by stevencohn** [comment] 2022-09-22 15:33
Looks like you were using the right one...

`Installer architecture (x64), OS architecture (x64), requesting (x64)`

**Comment by tridian-tn** [comment] 2022-09-22 15:36
OK, 64 bit version of the addin reinstalled. Powershell script output:

```
Versions...
OK Office version is 16.0
OK OneNote version is 15.0

AppID...
OK Registry::HKEY_CLASSES_ROOT\AppID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}

Root...
OK Registry::HKEY_CLASSES_ROOT\onemore

Shell...
OK Registry::HKEY_CLASSES_ROOT\onemore\shell\open\command
VERBOSE: "C:\Program Files\River\OneMoreAddIn\OneMoreProtocolHandler.exe" %1 %2 %3 %4 %5

AddIn...
OK Registry::HKEY_CLASSES_ROOT\River.OneMoreAddIn
OK Registry::HKEY_CLASSES_ROOT\River.OneMoreAddIn.1

CLSID...
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\InprocServer32\5.0.1.0
VERBOSE: Assembly = River.OneMoreAddIn, Version=5.0.1.0, Culture=neutral, PublicKeyToken=null
VERBOSE: CodeBase = C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll
VERBOSE: RuntimeVersion = runtimeVersion
VERBOSE: Class = River.OneMoreAddIn.AddIn
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\ProgID
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\Programmable
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\TypeLib
OK Registry::HKEY_CLASSES_ROOT\CLSID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}\VersionIndependentProgID

User...
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Classes\AppID\{88AB88AB-CDFB-4C68-9C3A-F10B75A5BC61}
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\OneNote\AddIns\River.OneMoreAddIn
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\River.OneMoreAddIn.dll
VERBOSE: C:\Program Files\River\OneMoreAddIn\River.OneMoreAddIn.dll
OK Registry::HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:

WebView2...
OK Registry::HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
OK location = C:\Program Files (x86)\Microsoft\EdgeWebView\Application
VERBOSE: version = 105.0.1343.42
VERBOSE: location = C:\Program Files (x86)\Microsoft\EdgeWebView\Application
```

**Comment by stevencohn** [comment] 2022-09-22 16:22
The it looks like OneMore is installed correctly.

I don't think I can solve this without an Insider build and I can't get that.

**Comment by stevencohn** [comment] 2022-09-22 16:24
One more test I can run. You have 32-bit OneNote. I'll try to install that. I've been running 64-bit for my tests.

**Comment by stevencohn** [comment] 2022-09-22 17:02
No luck. I can't get it to _not_ work! I'm at a loss I'm afraid. I'll keep an eye on it and if something comes up I'll give it a try but I just can't support Insider builds. I'm very sorry.

**Comment by tridian-tn** [comment] 2022-09-22 17:04
> No luck. I can't get it to _not_ work! I'm at a loss I'm afraid. I'll keep an eye on it and if something comes up I'll give it a try but I just can't support Insider builds. I'm very sorry.

No problem! Thanks for investigating. I'll stick qith 4.19 for now, take myself off the insider builds and when this version rolls out properly (quite soon I think), I'll try again.

**Comment by stevencohn** [comment] 2022-09-26 15:32
Closing until/unless I can diagnose with an Insider build of OneNote

**Closed by stevencohn** 2022-09-26 15:32 UTC
Labels: bug, no-repro, install
