### ISSUE TITLE
How does syntax coloring work?

### ISSUE THREAD

**Issue by akshaykhadse** [stevencohn/OneMore#487] opened 2022-04-01 04:32 UTC
I would like to understand the syntax coloring mechanism and fix the following issue.
https://github.com/stevencohn/OneMore/issues/486

Could you please provide any pointers to get started with this?

**Comment by stevencohn** [comment] 2022-04-01 09:47
That would we be awesome!

Each language is defined by is its [own file here](https://github.com/stevencohn/OneMore/tree/main/OneMore/Colorizer/Languages). C++ multiline comments are [defined here](https://github.com/stevencohn/OneMore/blob/ddde1f2b54eec7a1dd94e22f2dd00ba140690e6e/OneMore/Colorizer/Languages/cpp.json#L22).

Admittedly, it's a rudimentary parser and none of the language definitions are 100% complete. The strategy was to be simple and "good enough".

**Comment by stevencohn** [comment] 2022-04-10 11:30
Closing as a duplicate of #486

**Closed by stevencohn** 2022-04-10 11:30 UTC
