### ISSUE TITLE
Popup error

### ISSUE THREAD

**Issue by Silfra-glacier** [stevencohn/OneMore#1123] opened 2023-09-20 06:53 UTC
I don't know if this is my individual issue. When I open a onenote window, any program works normally; When I open the second Onenote window again, an error box will pop up along with the window. After clicking "OK All", there are no exceptions and all programs are running normally; Open more onenote windows afterwards and do not pop up again.😅
![image](https://github.com/stevencohn/OneMore/assets/68190236/9bcd30ce-0d98-41ba-9bcc-74692bdf503a)

**Comment by stevencohn** [comment] 2023-09-20 13:11
Marking this as a duplicate of #1058

**Closed by stevencohn** 2023-09-20 13:11 UTC
Labels: bug, duplicate
