### ISSUE TITLE
OneMore not showing up on Ribbon (3.22)

### ISSUE THREAD

**Issue by ptr2void** [stevencohn/OneMore#239] opened 2021-07-13 00:52 UTC
**Bug Description**
Not appearing on OneNote build 2106 Ribbon. Stays 'Inactive' on COM menu.

**To Reproduce**
1. Close OneNote and Send to OneNote
2. Install OneMore for Everyone
3. See error

**Expected behavior**
OneMore shows up on Ribbon

**Screenshots**
Can provide if needed

**Environment (if applicable):**
 - OneNote Version: Office 2019/O365, 64bit
 - OneMore Version: 3.22

**Additional context**
Have tried deleting all OneMore entries from Registry for clean install.

**OneMore Log Dump Below**

6796:1] Starting dllhost 6796, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0
6796:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
6796:1] ..OneAddInsUpdate(custom[]:0)
6796:1] ..building ribbon
6796:1] ..building ribbon colorizer commands
6796:1] ..RibbonLoaded()
6796:1] ..OnStartupComplete(custom[]:0)
6796:1] ..OneNote backup folder:: C:\Users\USER\AppData\Local\Microsoft\OneNote\16.0\Backup
6796:1] ..OneNote default folder: C:\Users\USER\Documents\OneNote Notebooks
6796:1] ..OneNote unfiled folder: C:\Users\USER\Documents\OneNote Notebooks\My Notebook\Quick Notes.one
6796:1] ..OneNote process module: C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.13127.20616)
6796:1] ..defining hotkeys
6796:1] ..ready
6796:1] Running command SettingsCommand
6796:9] Running command RunPluginCommand
6796:8] Running command ToCaseCommand
6796:9] Running command ToCaseCommand
6796:7] Running command ToCaseCommand
6796:10] Running command ToCaseCommand
6796:10] Running command ToCaseCommand
6796:9] Running command ToCaseCommand
6796:9] Running command ToCaseCommand
6796:9] Running command ToCaseCommand
6796:7] Running command ToCaseCommand
6796:8] Running command ToCaseCommand
6796:8] Running command ToCaseCommand
6796:9] Running command ToCaseCommand
6796:7] Running command ToCaseCommand
6796:7] Running command ToCaseCommand
6796:11] Running command ToCaseCommand

17280:1] Starting dllhost 17280, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0
17280:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
17280:1] ..OneAddInsUpdate(custom[]:0)
17280:1] ..building ribbon
17280:1] ..building ribbon colorizer commands
17280:1] ..RibbonLoaded()
17280:1] ..OnStartupComplete(custom[]:0)
17280:1] ..OneNote backup folder:: E:\cache\OneNote Backups\16.0\Backup
17280:1] ..OneNote default folder: C:\Users\USER\Documents\OneNote Notebooks
17280:1] ..OneNote unfiled folder: C:\Users\USER\Documents\OneNote Notebooks\My Notebook\Quick Notes.one
17280:1] ..OneNote process module: C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.13929.20386)
17280:1] ..defining hotkeys
17280:1] ..ready
17280:8] OnBeginShutdown(0)
17280:8] ..shutting down UI
17280:8] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,0)
17280:8] ..disposing 1 streams
17280:8] ..closing log

15384:1] Starting dllhost 15384, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0
15384:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
15384:1] ..OneAddInsUpdate(custom[]:0)
15384:1] ..building ribbon
15384:1] ..building ribbon colorizer commands
15384:1] ..RibbonLoaded()
15384:1] ..OnStartupComplete(custom[]:0)
15384:1] ..OneNote backup folder:: E:\cache\OneNote Backups\16.0\Backup
15384:1] ..OneNote default folder: C:\Users\USER\Documents\OneNote Notebooks
15384:1] ..OneNote unfiled folder: C:\Users\USER\Documents\OneNote Notebooks\My Notebook\Quick Notes.one
15384:1] ..OneNote process module: C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.14026.20270)
15384:1] ..defining hotkeys
15384:1] ..ready

15576:1] Starting dllhost 15576, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0
15576:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
15576:1] ..OneAddInsUpdate(custom[]:0)
15576:1] ..building ribbon
15576:1] ..building ribbon colorizer commands
15576:1] ..RibbonLoaded()
15576:1] ..OnStartupComplete(custom[]:0)
15576:1] ..OneNote backup folder:: E:\cache\OneNote Backups\16.0\Backup
15576:1] ..OneNote default folder: C:\Users\USER\Documents\OneNote Notebooks
15576:1] ..OneNote unfiled folder: C:\Users\USER\Documents\OneNote Notebooks\My Notebook\Quick Notes.one
15576:1] ..OneNote process module: C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.14026.20270)
15576:1] ..defining hotkeys
15576:1] ..ready
15576:8] OnBeginShutdown(0)
15576:8] ..shutting down UI
15576:8] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,0)
15576:8] ..disposing 1 streams
15576:8] ..closing log

10832:1] Starting dllhost 10832, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0
10832:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
10832:1] ..OneAddInsUpdate(custom[]:0)
10832:1] ..building ribbon
10832:1] ..building ribbon colorizer commands
10832:1] ..RibbonLoaded()
10832:1] ..OnStartupComplete(custom[]:0)
10832:1] ..OneNote backup folder:: E:\cache\OneNote Backups\16.0\Backup
10832:1] ..OneNote default folder: C:\Users\USER\Documents\OneNote Notebooks
10832:1] ..OneNote unfiled folder: C:\Users\USER\Documents\OneNote Notebooks\My Notebook\Quick Notes.one
10832:1] ..OneNote process module: C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.14026.20270)
10832:1] ..defining hotkeys
10832:1] ..ready
10832:1] Running command ToCaseCommand
10832:7] Running command ToCaseCommand
10832:11] Running command ToCaseCommand

20084:1] Starting dllhost 20084, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0
20084:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
20084:1] ..OneAddInsUpdate(custom[]:0)
20084:1] ..building ribbon
20084:1] ..building ribbon colorizer commands
20084:1] ..RibbonLoaded()
20084:1] ..OnStartupComplete(custom[]:0)
20084:1] ..OneNote backup folder:: E:\cache\OneNote Backups\16.0\Backup
20084:1] ..OneNote default folder: C:\Users\USER\Documents\OneNote Notebooks
20084:1] ..OneNote unfiled folder: C:\Users\USER\Documents\OneNote Notebooks\My Notebook\Quick Notes.one
20084:1] ..OneNote process module: C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.14131.20278)
20084:1] ..defining hotkeys
20084:1] ..ready
20084:9] Running command CropImageCommand

15152:1] Starting dllhost 15152, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0
15152:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
15152:1] ..OneAddInsUpdate(custom[]:0)
15152:1] ..building ribbon
15152:1] ..building ribbon colorizer commands
15152:4] ..RibbonLoaded()
15152:4] ..OnStartupComplete(custom[]:0)
15152:4] ..OneNote backup folder:: E:\cache\OneNote Backups\16.0\Backup
15152:4] ..OneNote default folder: C:\Users\USER\Documents\OneNote Notebooks
15152:4] ..OneNote unfiled folder: C:\Users\USER\Documents\OneNote Notebooks\My Notebook\Quick Notes.one
15152:4] ..OneNote process module: C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.14131.20278)
15152:4] ..defining hotkeys
15152:4] ..ready
15152:4] OnBeginShutdown(0)
15152:4] ..shutting down UI
15152:4] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,0)
15152:4] ..closing log

15068:1] Starting dllhost 15068, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0

14164:1] Starting dllhost 14164, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0

15936:1] Starting dllhost 15936, CPU=3501Mhz, en-US/en-US, v3.22, OneNote 15.0, Office 16.0

7516:1] Starting dllhost 7516, CPU=3501Mhz, en-US/en-US, v3.22, OneNote 15.0, Office 16.0

19084:1] Starting dllhost 19084, CPU=3501Mhz, en-US/en-US, v3.22, OneNote 15.0, Office 16.0

7040:1] Starting dllhost 7040, CPU=3501Mhz, en-US/en-US, v3.22, OneNote 15.0, Office 16.0

14800:1] Starting dllhost 14800, CPU=3501Mhz, en-US/en-US, v3.22, OneNote 15.0, Office 16.0

15996:1] Starting dllhost 15996, CPU=3501Mhz, en-US/en-US, v3.22, OneNote 15.0, Office 16.0

11048:1] Starting dllhost 11048, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0

3908:1] Starting dllhost 3908, CPU=3501Mhz, en-US/en-US, v3.19.4, OneNote 15.0, Office 16.0

14932:1] Starting dllhost 14932, CPU=3501Mhz, en-US/en-US, v3.22, OneNote 15.0, Office 16.0

**Comment by stevencohn** [comment] 2021-07-13 11:51
Sorry you're having problems. I'm not sure there's enough info here to debug the issue though. It looks like it was working, then at some point it stopped but I can't tell exactly when.

The plugin runs as a separate process named dllhost.exe which unfortunately many things run under. To identify which of those is the OneMore plugin, look at the first line in the log file "Starting dllhost <number>". That number is the process ID of the OneMore dllhost. Often, if you run into this problem, the dllhost didn't shut down properly and you need to stop it manually by killing that process. 

It can get into this state by stopping/restarting OneNote very quickly; the dllhost COM hosting environment doesn't have enough time to gracefully shut down or start up again.

So in your case because there was so much thrashing going on, the uninstaller should clean it up completely. Make sure the dllhost process is not running (can reboot too to clear it out if you're not sure which one) and then reinstall.

**Comment by jakkaas** [comment] 2021-07-23 00:55
I have been facing the same issue a few times before.

The issue seems to be with the installer. The x86 bit installer shows the default installation path for the x64 installer.

If I install it in the default path (program files) the update doesn't work. If I change the path and install it in the program file(x86) where the previous installation is present, then the above error of com "inactive" shows up.

I have found this issue a few times.

Recent 3.23, and 3.25 all updates I have checked show default installation path of x86 installation as that of x64 bit installer.

What I had to do was to look back at the old closed issue #119 and install the 3.10.1 x86 bit installer and it works.

Please have a look at this issue. I am forced in using the old updates.

**Comment by stevencohn** [comment] 2021-07-23 11:59
So #119 pointed out two solutions. 

1. Did you try the "install for all users" option? If OneNote is installed for all users then OneMore needs to be as well.
2. Did you try to delete the %APPDATA%\OneMore\settings.xml file? I didn't think I made breaking changes in there but just to be sure....

Meanwhile I see if I can repro the problem and sorry for the inconvenience.

**Comment by jakkaas** [comment] 2021-07-24 05:00
Yes, I Install for all users.

I did all the steps mentioned in #119.

The issue is that even after complete uninstall, I can only install the installation file with x86 architecture (The one which gives an option of direct installation in program file(x86)), which was the 3.10.1 x86 bit installer. If I download the file with x86 setup and it if gives an option of installation in program file rather than program file(x86), then in whichever folder I install, it won't work and fail to either detect or load.

Hope it makes sense.

**Comment by stevencohn** [comment] 2021-07-24 12:38
Do you have a physical 32-bit machine? Or you just have 32-bit OneNote installed?

I installed 32-bit OneNote on a 64-bit machine. Ran the OneMore_3.25_Setup86.msi, all users, default location (Program Files), and it installed and runs fine.

I installed again, this time setting the location to Program Files (x86) and it also runs fine.

I then installed OneMore_3.10.1_Setup86.msi, all users, default location (Program Files (x86)), ran and change a bunch of the OneMore settings - which upon restart, broke OneMore!

I uninstalled 3.10.1 and reinstalled 3.25. OneMore runs fine and recognizes the settings changes I made under 3.10.1.

So I do agree that the default location for the x86 installer needs to be fixed so it points to Program Files (x86). But other than that, I can't seem to break it.

**Comment by stevencohn** [comment] 2021-07-24 18:38
I've updated the build.ps1 script that builds the installer MSI files. This was incorrectly setting the default location for the x86 installer. But the location shouldn't matter. There are no differences between the compiled 32-bit and 64-bit OneMore binaries. The only difference is the installer itself. 

One a 32-bit machine, the x86 installer must be used. On a 64-bit machine, either installer can be used and the location is arbitrary.

So if the toolbar isn't showing up for you there must be something else going on.

@jakkaas  Do you have a copy of your OneMore log file? It would be in %TEMP%\OneMore.log

**Comment by jakkaas** [comment] 2021-07-25 17:12
I have a 64-bit machine.
I am not sure what is the issue. When I used to install a 64-bit installer in the program folder, OneMore never got updated. When I install 86 bit installer in the program folder/program file x86 folder it won't load. I have to forcefully load the 86 bit installer in the program file x86 folder, completely uninstall it and then install the 3.10.1 86 bit installer.
Then it gets updated to the 
[OneMore.log](https://github.com/stevencohn/OneMore/files/6874245/OneMore.log)
newest issue.

Today I installed a 3.26 86 bit installer. It got installed on the program file x86 folder. Now OneMore add-in is not seen in COM Add-ins.

I use a few add-in of onetastic, OneNote gem, OneNote highlight, etc. Is this the issue?
I have attached the link for the log file for your reference

https://drive.google.com/file/d/1STT5-TeFqXK5SEO_ofnwqBfYjl6VtJ_7/view?usp=sharing

**Comment by stevencohn** [comment] 2021-07-25 19:01
Did you try to modify the Languages\csharp.json file by adding a new rule but also commenting it out? It looks like this is the culprit. Those rule files are used to populate the Colorize menu and one can't be loaded it will fail. 

I'll add more exception handling to that load routine but if you remove the comment from csharp.json, I think it may load.

**Comment by stevencohn** [comment] 2021-07-25 19:08
Actually, sorry nix that. I tried adding a comment to csharp.json and it dump the exception to the log file but gracefully ignores the Colorize menu and continues running fine. So that must be a red herring in your log file.....

**Comment by jakkaas** [comment] 2021-07-26 05:39
Sorry, I am not a coding guy and I didn't make any modifications.

I tried installing 3.10.1 after 3.26 installation after OneMore was not showing on Add-in. It informed me that I can't install this version as the new version is already installed.

so I simply uninstalled OneMore from the control panel.

This is what I found in the installation folder after uninstallation

![image](https://user-images.githubusercontent.com/43289832/126938234-bd722faa-2f26-4288-a29f-97881b29f398.png)

Then I installed 3.10.1 and It got installed. After that when I checked OneNote, OneMore Add-in was showing up and it was found to be version 3.26

Here is the log file



[OneMore.log](https://github.com/stevencohn/OneMore/files/6875857/OneMore.log)

**Comment by stevencohn** [comment] 2021-07-26 10:25
1. Uninstall OneMore from Add/Remove Programs, or Apps and Features, or by rerunning the installer and choosing Remove
2. Delete Program Files\River\OneMoreAddin folder if it exists
3. Delete Program Files (x86)\River.OneMore folder if it exists
4. Delete %APPDATA%\OneMore folder if it exists
5. Install the latest OneMore

**Comment by stevencohn** [comment] 2021-07-29 19:57
As mentioned in #119, the last item in on the troubleshooting page seems to work: https://github.com/stevencohn/OneMore/wiki/Troubleshooting

Let me know if that works for you here and I'll close this ticket.

**Comment by jakkaas** [comment] 2021-07-30 07:35
Hey. You can close the ticket for now. I have not tried complete uninstallation and installation as it's working now. But once when I want to install a new update, I will do as mentioned. Thanks

**Closed** 2021-07-30 10:18 UTC
Labels: bug
