### ISSUE TITLE
Can you add PDF link page ffeature 

### ISSUE THREAD

**Issue by zhongguocn** [stevencohn/OneMore#363] opened 2021-12-23 01:24 UTC
**Is your feature request related to a problem? Please describe.**
OneNote can automatically generate linked pages when reading word documents. It will record the position of the page you are reading. After recording, click the mouse to jump to the page of the document.

Can you develop a function to generate link pages when reading PDF files.

**Describe the solution you'd like**

When reading a PDF file, take notes with OneNote, which can automatically record the page number position at that time and generate an open link.

I found an open source PDF reading software, which should be used to develop this function.Its configuration file can record the location and page number of PDF files.

The website is:
https://www.sumatrapdfreader.org/free-pdf-reader

**Comment by javathehunt** [comment] 2021-12-23 22:29
I think this is part of the Quicknote "Linked File" feature if I remember correctly? From the factory it was designed to work with only three programs Word, Powerpoint, and the MS browser. Having this feature for pdf would be pretty sweet. Even if the pdf needed to be embedded into the ON page but if it can link to an external pdf saved on the drive that would be even better.

I dabbled with this a bit but due to it being limited to those three apps I did not find much use for it. Something worth noting is that I belive you need to be logged into your MS account on ON and the target app - word, pp, browser - in order for the linking to work. Since the pdf app would not be a signed in MS acocunt this may be sometingn to be aware of.

**Comment by stevencohn** [comment] 2021-12-23 22:35
@javathehunt you're correct... this will only work with those three apps. Even with an open source app like @zhongguocn recommended, OneNote will not know how to associate notes with the app.

Regardless, I'm limited by the interop API that Microsoft exposes for add-ons like OneMore. I'm afraid this just may not be possible as a third-party developer.

**Comment by zhongguocn** [comment] 2021-12-24 05:41
@stevencohn @javathehunt 
Thank you for your reply. I can't judge whether the link page function of reading PDF is valuable.

But I'm sure it can be implemented with the aforementioned open source PDF reader. The file location and page number can be located in the configuration file of PDF reader.

We only need to link to the specified PDF page, and we don't need to accurately locate specific paragraphs. Would it be easier?

**Comment by stevencohn** [comment] 2021-12-25 02:26
This presumes that people would be willing to use that PDF reader as opposed to Adobe or other more popular readers. I don't want to bloat OneMore by installing this as well. I don't think this adds great value to OneMore in my opinion.

**Comment by stevencohn** [comment] 2022-01-07 00:11
I appreciate the suggestion. But closing it for now.

**Closed by stevencohn** 2022-01-07 00:11 UTC
Labels: answered
