### ISSUE TITLE
Can breadcrumb include notebook name?

### ISSUE THREAD

**Issue by andyylin** [stevencohn/OneMore#273] opened 2021-09-13 04:17 UTC
**Is your feature request related to a problem? Please describe.**
OneNote link sharing to a specific page doesn't always work well, so it'd be nice if when inserting a breadcrumb, the notebook name is included, so that colleagues can easily know which notebook to drill down in.

**Describe the solution you'd like**
At the beginning of a breadcrumb, add the notebook name.

**Comment by stevencohn** [comment] 2021-09-13 04:42
It should include the notebook name, followed by any hierarchy of section and section groups. If it's not including the notebook name, then there is a case that I do not know how to reproduce. Can you please give an example?

**Comment by stevencohn** [comment] 2021-09-13 04:48
My mistake, apparently, if the page is more than one level deep under a section group, it doesn't include the notebook name. I'll fix this.

**Comment by stevencohn** [comment] 2021-09-13 05:18
Duplicate of #272, will be fixed under that ticket.

**Closed by stevencohn** 2021-09-13 05:18 UTC
Labels: bug
