### ISSUE TITLE
Custom Styles change the direction from RTL to LTR also Onenote proofreading text from Hebrew to English language 

### ISSUE THREAD

**Issue by Alexnoj** [stevencohn/OneMore#613] opened 2022-09-19 10:23 UTC
Custom Styles change the direction from RTL to LTR also Onenote proofreading text from Hebrew to English language.

Onenote 365 64bit
Onemore 5.0V

**Comment by stevencohn** [comment] 2022-09-19 12:54
I'm unable to reproduce this with RTL Hebrew. Can you please give more detail or an example?

Proofreading from Hebrew to English? Not sure what you mean there.

**Comment by Alexnoj** [comment] 2022-09-20 07:57
First, Thanks for help.
Second, I upload images explain the problem. let me know if its good enought.

![Snag_77b4515](https://user-images.githubusercontent.com/30004592/191197541-ed4070aa-90e3-4eda-8bef-770b2f8e5a9e.png)

![image](https://user-images.githubusercontent.com/30004592/191198008-f98659f6-940e-47f4-94ae-7ac106289720.png)

![image](https://user-images.githubusercontent.com/30004592/191198834-0b819368-851a-42fa-943d-f2ce80a92a76.png)

![image](https://user-images.githubusercontent.com/30004592/191199882-157177f9-e718-4000-b5f5-3a00b6238991.png)

![image](https://user-images.githubusercontent.com/30004592/191200677-5c34227b-e3fe-4fbe-ae96-76940f9e88ff.png)

**Comment by stevencohn** [comment] 2022-09-20 11:39
I was able to reproduce it using this example. It's due to the fact that you have English text alongside Hebrew and even though you've selected Right to Left from the alignment menu, English text internally is treated as left to right so it's confusing OneMore. I can fix it but I'm also curious:

What's the overall language of the page? Is it Hebrew or English?
What's your default Windows language set to? It looks like English because your menus are in English.

Thanks

**Comment by Alexnoj** [comment] 2022-09-20 11:55
language of the page is Hebrew
Windows is on Eng (I had hebrew its not change)
onenote is on Hebrew- I change it to english only for print screen.

**Comment by stevencohn** [comment] 2022-09-20 13:04
Sadly, there seems to be a bug in the OneNote extension framework. It hands OneMore an XML document. If I immediately hand that back unmodified to OneNote, OneNote will change it to what you're seeing. There doesn't seem to be a way around that.

Note that I've only seen this happen when a single line (paragraph) of text contains both RTL and LTR text. OneNote will normalize the paragraph to one or the other.

**Comment by stevencohn** [comment] 2022-09-20 23:22
Bug report submitted to Microsoft here: https://feedbackportal.microsoft.com/feedback/idea/ad040a45-3a39-ed11-a81b-6045bd7fe4d3

I'm not holding my breath waiting for them to fix it but we'll see...

Closing this for now since there's nothing left to do.

**Closed by stevencohn** 2022-09-20 23:22 UTC
Labels: bug, onenote-bug
