### ISSUE TITLE
The Increase font and decrease font buttons do not seem to work

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#50] opened 2020-09-22 02:10 UTC
I select the text I want to change and then I either use the quick access bar or the OneMore ribbon button but none of them is working

**Comment by stevencohn** [comment] 2020-09-22 12:04
They all seem to work for me. I can't reproduce this.
Is there anything in the OneMore log file when you try these commands? This can be accessed from a link on the About box

**Comment by 1001QAdotNET** [comment] 2020-09-22 13:07
Yes here is the message

14792:10] Error executing AlterSizeCommand
14792:10] EXCEPTION - System.ArgumentException
Message...: An item with the same key has already been added.
StackTrace:    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at River.OneMoreAddIn.AlterSizeCommand.UpdateSpanStyle(XElement span)
   at River.OneMoreAddIn.AlterSizeCommand.AlterElementsByValue()
   at River.OneMoreAddIn.AlterSizeCommand.Execute(Int32 delta)
TargetSite: [mscorlib] System.ThrowHelper::ThrowArgumentException()

**Comment by stevencohn** [comment] 2020-09-22 16:03
OK. It's surprising because that scenario should be possible but I've updated the code to correct for it. I'll check it in later and push out a patch

**Comment by stevencohn** [comment] 2020-09-23 15:52
Fixed in release 2.15

**Comment by 1001QAdotNET** [comment] 2020-09-23 20:01
It is still there. Dont remember if these (increase font decrease font) were added to the context menu 
Also if you cod add the paragraph spacing option to the context menu it would be great 
![image](https://user-images.githubusercontent.com/17384308/94063294-e1f41880-fdb5-11ea-9ab0-ec94ca68a63c.png)

20804:3] Error executing AlterSizeCommand
20804:3] EXCEPTION - System.NullReferenceException
Message...: Object reference not set to an instance of an object.
StackTrace:    at River.OneMoreAddIn.AlterSizeCommand.<>c.<AlterCDataByValue>b__7_1(XCData n)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at River.OneMoreAddIn.AlterSizeCommand.AlterCDataByValue()
   at River.OneMoreAddIn.AlterSizeCommand.Execute(Int32 delta)
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.AlterSizeCommand+<>c::<AlterCDataByValue>b__7_1()

20804:3] AboutCommand.Execute()

**Comment by stevencohn** [comment] 2020-09-23 20:06
Hm, that's a different error. I'll take a look.

I can't add the paragraph spacing dialog to the context menu without duplicating and re-implementing that functionality myself and OneMore is about adding "new" functionality. 

Sounds like you're doing an aweful lot of copying/pasting from somewhere and want to do a lot of reformatting of the content. I think applying a style theme might help you. Under Custom Styles, load or create a style theme and then use the Apply Styles to Page command.

**Comment by stevencohn** [comment] 2020-09-23 20:10
For the exception you saw in Alter Size, if it's not private or sensitive information, would it be possible to save that page as XML and send it to me or attach to this discussion (I'll delete it once I have it if you want)

**Comment by 1001QAdotNET** [comment] 2020-09-23 20:21
Sure ..in a meeting now give me like 30 mins

**Comment by 1001QAdotNET** [comment] 2020-09-23 21:31
<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{E173161C-E37C-0605-1FFF-C479FCD365B6}{1}{E1955603164008642421821994431337767626686751}" name="Test page" dateTime="2020-09-23T21:10:45.000Z" lastModifiedTime="2020-09-23T21:27:48.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="13.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="2" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="11.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE author="Microsoft account" authorInitials="Ma" authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedBy="Microsoft account" lastModifiedByInitials="Ma" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:27:47.000Z" lastModifiedTime="2020-09-23T21:27:47.000Z" objectID="{2280162E-7762-4EB9-A5FC-2B89044A039E}{27}{B0}" alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[Test page]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline author="Microsoft account" authorInitials="Ma" lastModifiedBy="Microsoft account" lastModifiedByInitials="Ma" lastModifiedTime="2020-09-23T21:27:47.000Z" objectID="{2280162E-7762-4EB9-A5FC-2B89044A039E}{15}{B0}">
    <one:Position x="108.0" y="68.4000015258789" z="0" />
    <one:Size width="118.9581756591797" height="47.60740280151367" />
    <one:OEChildren>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:27:47.000Z" lastModifiedTime="2020-09-23T21:27:47.000Z" objectID="{2280162E-7762-4EB9-A5FC-2B89044A039E}{16}{B0}" alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[Line1]]></one:T>
      </one:OE>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:27:47.000Z" lastModifiedTime="2020-09-23T21:27:47.000Z" objectID="{2280162E-7762-4EB9-A5FC-2B89044A039E}{21}{B0}" alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[Line2]]></one:T>
      </one:OE>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:27:47.000Z" lastModifiedTime="2020-09-23T21:27:47.000Z" objectID="{2280162E-7762-4EB9-A5FC-2B89044A039E}{23}{B0}" alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[Text text text text]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
  <one:Outline selected="partial" author="Microsoft account" authorInitials="Ma" lastModifiedBy="Microsoft account" lastModifiedByInitials="Ma" lastModifiedTime="2020-09-23T21:27:48.000Z" objectID="{8FC42D8E-57E9-443F-8B59-B1D99A61ED04}{145}{B0}">
    <one:Position x="468.0" y="158.4000091552734" z="1" />
    <one:Size width="72.0" height="13.42771339416504" />
    <one:OEChildren selected="partial">
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:27:48.000Z" lastModifiedTime="2020-09-23T21:27:48.000Z" objectID="{8FC42D8E-57E9-443F-8B59-B1D99A61ED04}{146}{B0}" alignment="left" quickStyleIndex="2" selected="partial">
        <one:T selected="all"><![CDATA[]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>


20804:3] Error executing AlterSizeCommand
20804:3] EXCEPTION - System.NullReferenceException
Message...: Object reference not set to an instance of an object.
StackTrace:    at River.OneMoreAddIn.AlterSizeCommand.<>c.<AlterCDataByValue>b__7_1(XCData n)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at River.OneMoreAddIn.AlterSizeCommand.AlterCDataByValue()
   at River.OneMoreAddIn.AlterSizeCommand.Execute(Int32 delta)
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.AlterSizeCommand+<>c::<AlterCDataByValue>b__7_1()


So with the above page I just discovered that if I select text and press increase size it is not working
If I do not select any text on the page but I press Increase font size again the font is increased


For this page (same notebook hosted in OneDrive as the one above, in the same section) everything works as expected

<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{E173161C-E37C-0605-1FFF-C479FCD365B6}{1}{E19549400855643899315120171230674262289642521}" name="test" dateTime="2020-06-01T15:56:34.000Z" lastModifiedTime="2020-09-23T21:30:58.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="11.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE author="Ce Pe" authorInitials="CP" authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;Cs2NblhtN9OCDkkFMVGjiQ==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedBy="Ce Pe" lastModifiedByInitials="CP" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;Cs2NblhtN9OCDkkFMVGjiQ==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:30:58.000Z" lastModifiedTime="2020-09-23T21:30:58.000Z" objectID="{29AF836D-543D-4311-94F2-3FDD975F24BB}{15}{B0}" alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[test]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial" author="Microsoft account" authorInitials="Ma" lastModifiedBy="Microsoft account" lastModifiedByInitials="Ma" lastModifiedTime="2020-09-23T21:30:58.000Z" objectID="{E40D77ED-E2D1-0E65-2FBA-F5E2FDE9713B}{40}{B0}">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="147.8898468017578" height="84.859375" />
    <one:OEChildren selected="partial">
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:30:58.000Z" lastModifiedTime="2020-09-23T21:30:58.000Z" objectID="{E40D77ED-E2D1-0E65-2FBA-F5E2FDE9713B}{66}{B0}" alignment="left" spaceBefore="5.5" spaceAfter="5.5" quickStyleIndex="1" selected="partial" style="font-family:Calibri;font-size:15.0pt">
        <one:T selected="all"><![CDATA[Line1]]></one:T>
      </one:OE>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:30:58.000Z" lastModifiedTime="2020-09-23T21:30:58.000Z" objectID="{E40D77ED-E2D1-0E65-2FBA-F5E2FDE9713B}{69}{B0}" alignment="left" spaceBefore="5.5" spaceAfter="5.5" quickStyleIndex="1" selected="partial" style="font-family:Calibri;font-size:15.0pt">
        <one:T selected="all"><![CDATA[Line2]]></one:T>
      </one:OE>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:30:58.000Z" lastModifiedTime="2020-09-23T21:30:58.000Z" objectID="{E40D77ED-E2D1-0E65-2FBA-F5E2FDE9713B}{72}{B0}" alignment="left" spaceBefore="5.5" spaceAfter="5.5" quickStyleIndex="1" selected="partial" style="font-family:Calibri;font-size:15.0pt">
        <one:T selected="all"><![CDATA[Text text text text]]></one:T>
      </one:OE>
      <one:OE authorResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" lastModifiedByResolutionID="&lt;resolutionId provider=&quot;Windows Live&quot; hash=&quot;sbFZHWO7HYEIJrCF4+h9og==&quot;&gt;&lt;localId cid=&quot;a0f36009f81fb3af&quot;/&gt;&lt;/resolutionId&gt;" creationTime="2020-09-23T21:30:58.000Z" lastModifiedTime="2020-09-23T21:30:58.000Z" objectID="{E40D77ED-E2D1-0E65-2FBA-F5E2FDE9713B}{60}{B0}" alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>

**Comment by 1001QAdotNET** [comment] 2020-09-23 21:36
Re-what I am doing
My work with OneNote is for studying.
The workflow is this:
I copy and paste the text from an Oreilly book and then I start reading
As I read I highlight important things
I have a script that extracts these at the end the reading
I collapse unimportant paragraphs or paragraphs that I am done with

Due to copy and paste some of the text gets a weird format and I fix that as I go 
For the same reasons spaces between paragraphs and empty lines show up and I need to remove these

I am sure I am not the only one doing this (I am seeing similar requests to clean up and format the doc coming from others)

**Comment by stevencohn** [comment] 2020-09-23 22:02
OK I think I fixed the main error. Release 2.15.1

I know about the problem with not resizing selected text. That will require a bit more rework. I've been avoiding it but I'll get to it... ;-)

**Comment by 1001QAdotNET** [comment] 2020-09-23 22:12
OK thank you!
I am preparing something for work now. 
As soon as I get this done I will start testing the plugin 
I need to learn how to work with XML it should not be that difficult

**Comment by stevencohn** [comment] 2020-10-27 14:24
So adjusting font size of a selected region is working, as is the entire page if no selection is currently active. I've tested it a number of ways and it seems to work OK.

Please let me know if you think there is still a problem, otherwise I'll close this out in a couple of days

**Closed** 2020-11-02 17:15 UTC
Labels: bug, done
