### ISSUE TITLE
Performance issues in 6.5.0

### ISSUE THREAD

**Issue by cspotcode** [stevencohn/OneMore#1520] opened 2024-08-02 23:11 UTC
I get some pretty bad performance issues on 6.5.0.  OneNote becomes unresponsive for several seconds at a time.  I downgraded to 6.4.0 and the problem went away.

It happens sometimes when I'm typing normally in a page, the screen will freeze and I have to wait a few seconds for the letters I typed to appear.

I can also trigger it pretty reliably by opening and closing the command palette.  The UI will freeze, so either opening or closing the command palette's will be delayed, will freeze for a few seconds.

These are my only guesses as to what's causing it:
https://github.com/stevencohn/OneMore/issues/1422#issuecomment-2256851015
https://github.com/stevencohn/OneMore/issues/1517

Hopefully this doesn't seem like issue spam, I wasn't sure the best way to report this, wasn't sure if it was related to either of those linked issues, and wasn't sure what additional information that would be helpful to debug.

**Comment by stevencohn** [comment] 2024-08-03 00:02
This is actually a known problem and a duplicate of #1506, related to the Hashtag upgrade process being stuck in a pending state.  See [this comment](https://github.com/stevencohn/OneMore/issues/1506#issuecomment-2254097195).

The hashtag catalog is stored in the OnMore.db database file. You can safely delete this file and the scanner will rebuild it from scratch. The key is to schedule the rebuild after you restart OneNote, which you can do from the command palette, entering the command "Schedule Hashtag Scan", and choosing the notebooks to scan - you can safely select them all.

I'm going to mark this as a duplicate of #1506, close this, and track it from there.

**Closed by stevencohn** 2024-08-03 00:02 UTC
Labels: bug, duplicate
