### ISSUE TITLE
The function of converting to code blocks leads to a significant slowdown in OneNote's performance until it becomes unresponsive.

### ISSUE THREAD

**Issue by daiyeci** [stevencohn/OneMore#1323] opened 2024-03-08 14:09 UTC
I am encountering an issue with a plugin where, upon attempting to convert content into a code module within OneNote, the interface starts loading sluggishly and eventually turns completely white. Despite repeating this operation multiple times, the outcome remains the same. After restarting my computer, I tried resolving the issue using a maintenance update version 6.1.0 mis, . However, during the execution of the repair process, the software reported an error. The specific details of the error message are as follows:
`onemoreSetup.log`

This issue where converting to code blocks causes OneNote to slow down significantly and eventually become unresponsive did not occur in version 5, but started happening after upgrading to version 6.0.1. Even after updating to the latest version 6.1.0, this problem has not been resolved.
======================================================================
starting action: --install .. 2024/3/8 21:43:12
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated
on behalf of WORKGROUP\system

CheckBitnessAction.Install ---
Installer architecture (x64), OS architecture (x64), requesting (x64)

Register... version 6.1.0

CheckOneNoteAction.Install ---
VerifyOneNoteApplication()
... checking HKEY_CLASSES_ROOT\OneNote.Application
... found CLSID {DC67E480-C3CB-49F8-8232-60B0C2056C8E}
... found CurVer OneNote.Application.15
... OK
VerifyRootClass(CLSID)
... checking HKEY_CLASSES_ROOT\CLSID\{DC67E480-C3CB-49F8-8232-60B0C2056C8E}
... verified InprocServer32 Microsoft.Office.Interop.OneNote, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71E9BCE111E9429C
... verified ProgID as OneNote.Application.15
... found TypeLib as {0EA692EE-BB50-4E3C-AEF0-356D91732725}
... verified VersionIndependentProgID as OneNote.Application.15
... OK
VerifyRootClass(WOW6432Node\CLSID)
... checking HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{DC67E480-C3CB-49F8-8232-60B0C2056C8E}
... verified InprocServer32 Microsoft.Office.Interop.OneNote, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71E9BCE111E9429C
... verified ProgID as OneNote.Application.15
... found TypeLib as {0EA692EE-BB50-4E3C-AEF0-356D91732725}
... verified VersionIndependentProgID as OneNote.Application.15
... OK
VerifyRootClass(Software\Classes\CLSID)
... checking HKEY_LOCAL_MACHINE\Software\Classes\CLSID\{DC67E480-C3CB-49F8-8232-60B0C2056C8E}
... verified InprocServer32 Microsoft.Office.Interop.OneNote, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71E9BCE111E9429C
... verified ProgID as OneNote.Application.15
... verified TypeLib as {0EA692EE-BB50-4E3C-AEF0-356D91732725}
... verified VersionIndependentProgID as OneNote.Application.15
... OK
VerifyCurVer()
... checking HKEY_CLASSES_ROOT\OneNote.Application.15
... verified CLSID {DC67E480-C3CB-49F8-8232-60B0C2056C8E}
... OK
VerifyTypeLib()
... checking HKEY_CLASSES_ROOT\TypeLib\{0EA692EE-BB50-4E3C-AEF0-356D91732725}
... verified Microsoft.Office.Interop.OneNote, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71E9BCE111E9429C
... verified Win32 Object Library C:\Program Files\Microsoft Office\Root\Office16\ONENOTE.EXE\3
... verified win64 Object Library C:\Program Files\Microsoft Office\Root\Office16\ONENOTE.EXE\3
... OK

ShutdownOneNoteAction.Install ---
dllhost process not found
stopping process ONENOTE, pid 2600
ONENOTE process termination confirmed

ProtocolHandlerAction.Install ---
step 0: opening HKLM:\Software\Classes\onemore
step 1: setting properties of HKLM:\Software\Classes\onemore
step 2: opening HKLM:\Software\Classes\onemore\shell\open\command
step 3: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command

TrustedProtocolAction.Install ---
translating user LAPTOP-2VLDE1OG\system to SID
LAPTOP-2VLDE1OG\system identity not mapped, falling back
fallback to search username in HKEY_USERS
defaulting Office version to 16
step 4: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
install failed; error registering
System.ArgumentNullException
Message: 值不能为 null。
参数名: name
Source: mscorlib
StackTrace:    在 System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   在 Microsoft.Win32.RegistryKey.ValidateKeyName(String name)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 OneMoreSetupActions.TrustedProtocolAction.Install()
   在 OneMoreSetupActions.Program.Install()
TargetSite: [mscorlib] System.ThrowHelper::ThrowArgumentNullException()

**Comment by daiyeci** [comment] 2024-03-08 14:12
[Uploading OneMore.log…]()

**Comment by daiyeci** [comment] 2024-03-08 14:13
[OneMore.log](https://github.com/stevencohn/OneMore/files/14539076/OneMore.log)

**Comment by daiyeci** [comment] 2024-03-08 15:41
Please check 
[05Python中的函数.zip](https://github.com/stevencohn/OneMore/files/14540071/05Python.zip)

**Comment by stevencohn** [comment] 2024-03-10 17:09
This appears to be reproducible. I've not yet confirmed if this ticket is a duplicate of #1306 so am reopening this one for now.

**Comment by stevencohn** [comment] 2024-04-28 13:25
Hi, this is not the answer you'll want to hear but, after some testing, it's pretty evident that this is a limitation of the way add-ins communicate with OneNote. Even though this example page is over 1MB in size, the OneMore add-in is pretty quick at reading the page and making the changes. But when it stalls when attempting it asks OneNote to save the updated page.

In general, there's nothing that can be done to solve this.

However, what you might consider is breaking up the page either into separate sub-pages, or dividing it up into separate Outline containers - the gray box that surrounds your page content. OneMore is good at saving only updating Outlines rather than the entire page. I realize this makes your example page quite complex so may not be practical in this case.

I'm sorry I don't have better news. It's just the way Microsoft has designed the add-in architecture unfortunately.

**Closed** 2024-05-05 10:57 UTC
Labels: bug, answered, onenote-bug
