### ISSUE TITLE
Ribbon icons disappear when opening multiple instances of OneNote

### ISSUE THREAD

**Issue by zoidy** [stevencohn/OneMore#1576] opened 2024-09-19 19:42 UTC
# Problem to Solve

When opening multiple instances of OneNote, certain OneMore buttons are missing either their text or their icon.

# To Reproduce

1. Open one instance of OneNote. Observe the OneMore toolbar appears correctly
2. Open a second instance by Shift+left cliking the Windows taskbar OneNote Icon

# Expected Behavior

Buttons are rendered correctly.

# Screenshots

![ONENOTE_2024-09-19_15-39-10](https://github.com/user-attachments/assets/b767ea7b-8dbf-46d2-a1b7-362cb65b645a)
![ONENOTE_2024-09-19_15-39-55](https://github.com/user-attachments/assets/0026e982-d7ac-464b-b732-05dec586004a)

# Environment (if applicable)
OneMore Version 6.5.1 with OneNote 16.0.17928.20156

# Additional Context

I recently upgraded from an older version of OneMore (I'm not sure which one exactly but it was at least a year or two old. The issue did not occur on that version.

**Comment by stevencohn** [comment] 2024-09-19 21:26
I believe this is a duplicate of #1058. See this comment https://github.com/stevencohn/OneMore/issues/1058#issuecomment-1642570666

**Closed** 2024-09-19 21:27 UTC
Labels: bug, duplicate

**Comment by jasonjac2** [comment] 2024-09-20 11:28
Work around - use CTRL+M to open a second window.
