### ISSUE TITLE
Merge cells in a table

### ISSUE THREAD

**Issue by ankiman1** [stevencohn/OneMore#1345] opened 2024-04-11 17:32 UTC
Hi, there is a method to merge cells into a single cell with the add in ? (like in the photo) 

![question](https://github.com/stevencohn/OneMore/assets/166498817/f4a354bb-f0ea-4f70-bb5d-90f6ea173e48)

**Comment by stevencohn** [comment] 2024-04-11 18:34
Duplicate of #1342 

No this is not possible in OneNote. OneNote uses a proprietary table format that does not allow cell merges. While other OneNote plugins have claimed to be able to do this, it's not actually cell merging. Those solution use a "trick" where they overlay an Outline on top of a table; this is very fragile and easy to break.

**Comment by ankiman1** [comment] 2024-04-11 18:50
Thank you :)
 (sorry for create a duplicate, i did not see the post #1342 )

**Closed** 2024-04-25 02:55 UTC
Labels: duplicate, question, answered
