### ISSUE TITLE
Feature request: add the option to select any text and add arbitrary attributes to the selected text

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#52] opened 2020-09-23 13:01 UTC
The tag feature is great in OneNote
Unfortunately, as far as I can see, it can be added to paragraphs `<p>` only 
Would it be possible for you to implement the option to select text and add an attribute to the selected text?  (I would use these attributes as tags) 
There is a surrogate solution for this by using background colors but then you need one more step to map the color to a certain tag, it is a little bit convoluted and not very flexible

Related to the above -this could be implemented with the new plugin option IF the OneMore end could also pass as a second parameter, the selected text.  After that the plugin I would write would look for that fragment in the file and I would process it myself. 
Probably a creative way to do that is to mark the text with a designated color -that would create a <span> with that specific color as attribute -assuming it will be unique and that is nowhere else in the file then a plugin could look for that and change it into an attribute 
It will be very convoluted since I need to mark the text and then press the plugin button....

**Comment by stevencohn** [comment] 2020-09-23 15:53
Duplicate of #51

**Closed by stevencohn** 2020-09-23 15:53 UTC
