### ISSUE TITLE
copy as  markdown report an error

### ISSUE THREAD

**Issue by zhangzikai** [stevencohn/OneMore#810] opened 2022-12-25 05:12 UTC
Describe the bug

copy as  markdown report an error
To Reproduce
1.click  "copy as markdown " button
2.an error ocurred

Expected behavior
...

Screenshots
![Snipaste_2022-12-25_13-11-50](https://user-images.githubusercontent.com/18569635/209457611-17b83a77-68e4-420c-a560-8ecc4370389d.png)

Environment (if applicable):

OneNote Version: Microsoft® OneNote® 适用于 Microsoft 365MSO (版本 2212 Build 16.0.15928.20002) 64 位
OneMore Version 5.4.2
Additional context
10408:5] SaveToMRU using derived name CopyAsMarkdownCmd
10408:15] Running command CopyAsMarkdownCommand
10408:16] 运行命令CopyAsMarkdownCommand时出错
10408:16] System.Runtime.InteropServices.COMException
Message: OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
Description: Unrecognized error code 0x800401D0
ErrorCode: 0x800401D0 (-2147221040)
HResult: 0x800401D0 (-2147221040)
Source: mscorlib
StackTrace:    在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
   在 System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   在 System.Windows.Clipboard.SetDataInternal(String format, Object data)
   在 River.OneMoreAddIn.ClipboardProvider.<>c__DisplayClass11_0.<SetText>b__0()
   在 River.OneMoreAddIn.SingleThreaded.<>c__DisplayClass1_0.<Invoke>b__0()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 River.OneMoreAddIn.ClipboardProvider.<SetText>d__11.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 River.OneMoreAddIn.Commands.MarkdownWriter.<Copy>d__12.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 River.OneMoreAddIn.Commands.CopyAsMarkdownCommand.<Execute>d__1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 River.OneMoreAddIn.CommandFactory.<Run>d__5.MoveNext()
TargetSite: [mscorlib] System.Runtime.InteropServices.Marshal::ThrowExceptionForHRInternal()

10408:16] SaveToMRU using derived name CopyAsMarkdownCmd

Thanks .

**Comment by stevencohn** [comment] 2023-01-16 16:06
Cannot reproduce. If there is any other context around this that you can provide, that would be greatly appreciated

**Comment by stevencohn** [comment] 2023-01-17 17:46
may be fixed by refactoring behind #802

**Closed by stevencohn** 2023-01-17 17:46 UTC
Labels: bug, no-repro
