### ISSUE TITLE
XML Show freeze

### ISSUE THREAD

**Issue by gjblack71** [stevencohn/OneMore#627] opened 2022-09-26 20:58 UTC
**Describe the bug**
XML window freezes itself and Onenote app.

**To Reproduce**
1. Go to 'Show XML'
2. Click out of 'OneMore XML window' onto Onenote window (note: clicking onto other windows like notepad have expected behaviour)
3. Onenote as well as XML window freezes.

**Environment (if applicable):**
 - OneNote Version: O365,  64bit . Office Insider Beta version 2210
 - OneMore Version both 5.0 and 5.1

**Additional context**
12584:1] Starting dllhost 12584, CPU=2419Mhz, en-US/en-US, v5.1.0, OneNote 15.0, Office 16.0
12584:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15715.20014)
12584:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
12584:1] ..OneAddInsUpdate(custom[])
12584:1] ..building ribbon
12584:1] ..building ribbon colorizer commands
12584:1] ..OnStartupComplete(custom[])
12584:4] ..defining 43 hotkeys for input locale 3081
12584:1] ..starting command service
12584:1] ..starting reminder service
12584:1] ..ready
12584:5] Running command UpdateCommand
12584:1] Running command ShowXmlCommand
12584:1] ..XmlDialog loaded page, scope Selection, 1499 chars

**Comment by stevencohn** [comment] 2022-09-26 21:13
Can't reproduce even after setting locale to Australia (which I didn't expect to have any bearing but...)

Is there anything else you can tell me about your configuration, setup, steps to reproduce?

**Comment by gjblack71** [comment] 2022-09-26 21:16
Office Insider Beta 2210 version (latest). Do have other addins but tested with them disabled via com add-ins option in Onenote settings. I also have moved Onenote cache to different partition.

**Comment by stevencohn** [comment] 2022-09-26 21:33
I don't have access to Insider builds. Others have reported problems with Insider builds too but I can't seem to repro them with the latest public builds.

**Comment by stevencohn** [comment] 2022-11-09 15:15
Closing for now

**Closed by stevencohn** 2022-11-09 15:15 UTC
Labels: bug, no-repro
