### ISSUE TITLE
Links References command not working?

### ISSUE THREAD

**Issue by Cossackx** [stevencohn/OneMore#1568] opened 2024-09-03 19:43 UTC
# Problem to Solve

- Generate Bi-directional links based on Title not working

# Environment (if applicable)

 - OneNote Version: O365,  64bit?]
 - OneMore Version latest

**Comment by stevencohn** [comment] 2024-09-03 19:47
What you seeing happen? It should allow title-body or title-title linking.

**Comment by Cossackx** [comment] 2024-09-03 20:04
No error. No nothing really. It does have the starting dialogue box. See video:

https://github.com/user-attachments/assets/e1a55902-ba46-46cb-a31d-b6178edd5522

Log file:
05|03:59:59.832| Log restarted
19|04:00:02.019| Running command LinkReferencesCommand
07|04:00:06.549| ..searching for 'Note 4'
07|04:00:06.589| ..searching for matches on ''
07|04:00:06.589| ..search not found on Test Notebook/New Section 1/Untitled page
07|04:00:06.597| ..searching for matches on 'Note 1'
07|04:00:06.597| ..search not found on Test Notebook/New Section 2/Note 1
07|04:00:06.605| ..searching for matches on 'Note 2'
07|04:00:06.605| ..search not found on Test Notebook/New Section 2/Note 2
07|04:00:06.613| ..searching for matches on 'Note 3'
07|04:00:06.613| ..search not found on Test Notebook/New Section 2/Note 3
07|04:00:06.613| ..00:00.08 linking complete
07|04:00:06.614| progress dialog completed
08|04:00:42.560| hashtag service scanned 8 times in the last hour, averaging 15ms
04|04:00:44.625| Running command LinkReferencesCommand
16|04:00:50.881| ..searching for 'Note 1'
16|04:00:50.934| ..searching for matches on ''
16|04:00:50.934| ..search not found on Test Notebook/New Section 1/Untitled page
16|04:00:50.943| ..searching for matches on 'Note 2'
16|04:00:50.943| ..search not found on Test Notebook/New Section 2/Note 2
16|04:00:50.953| ..searching for matches on 'Note 3'
16|04:00:50.953| ..search not found on Test Notebook/New Section 2/Note 3
16|04:00:50.961| ..searching for matches on 'Note 4'
16|04:00:50.961| ..search not found on Test Notebook/New Section 2/Note 4
16|04:00:50.961| ..00:00.09 linking complete
16|04:00:50.961| progress dialog completed
04|04:00:56.750| Running command LinkReferencesCommand
07|04:01:02.696| ..searching for 'Note 2'
07|04:01:02.750| ..searching for matches on ''
07|04:01:02.750| ..search not found on Test Notebook/New Section 1/Untitled page
07|04:01:02.759| ..searching for matches on 'Note 1'
07|04:01:02.759| ..search not found on Test Notebook/New Section 2/Note 1
07|04:01:02.769| ..searching for matches on 'Note 3'
07|04:01:02.769| ..search not found on Test Notebook/New Section 2/Note 3
07|04:01:02.778| ..searching for matches on 'Note 4'
07|04:01:02.778| ..search not found on Test Notebook/New Section 2/Note 4
07|04:01:02.778| ..00:00.09 linking complete
07|04:01:02.778| progress dialog completed
14|04:01:10.286| Running command LinkReferencesCommand
12|04:01:16.342| ..searching for 'Note 3'
12|04:01:16.376| ..searching for matches on ''
12|04:01:16.376| ..search not found on Test Notebook/New Section 1/Untitled page
12|04:01:16.385| ..searching for matches on 'Note 1'
12|04:01:16.385| ..search not found on Test Notebook/New Section 2/Note 1
12|04:01:16.393| ..searching for matches on 'Note 2'
12|04:01:16.393| ..search not found on Test Notebook/New Section 2/Note 2
12|04:01:16.401| ..searching for matches on 'Note 4'
12|04:01:16.401| ..search not found on Test Notebook/New Section 2/Note 4
12|04:01:16.401| ..00:00.07 linking complete
12|04:01:16.401| progress dialog completed
04|04:01:22.641| Running command LinkReferencesCommand
13|04:01:28.176| ..searching for 'Note 4'
13|04:01:28.216| ..searching for matches on ''
13|04:01:28.216| ..search not found on Test Notebook/New Section 1/Untitled page
13|04:01:28.225| ..searching for matches on 'Note 1'
13|04:01:28.226| ..search not found on Test Notebook/New Section 2/Note 1
13|04:01:28.234| ..searching for matches on 'Note 2'
13|04:01:28.234| ..search not found on Test Notebook/New Section 2/Note 2
13|04:01:28.242| ..searching for matches on 'Note 3'
13|04:01:28.242| ..search not found on Test Notebook/New Section 2/Note 3
14|04:01:28.242| ..00:00.08 linking complete
14|04:01:28.242| progress dialog completed
13|04:02:11.541| Running command AboutCommand

**Comment by stevencohn** [comment] 2024-09-03 20:08
Oh, that the Link References command, not the Bi-directional Linking commands! OK, let me try to reproduce based on your video. Thanks.

**Comment by stevencohn** [comment] 2024-09-03 20:22
I'm going to blame this on Windows Search, which is a reasonable conclusion since it's bit me in the past in so many similar cases. Link References uses Windows Search to try to find the titled page; this is why the log file mentions "search" and "searching". I can circumvent that with minimal impact on performance, hopefully. 

I'll get it in the next release.

**Comment by Cossackx** [comment] 2024-09-03 20:54
Thank you! Just confirming. No fix after doing these [troubleshooters](https://onemoreaddin.com/get-started/Troubleshooting.htm)...

OneNote Specific Problems

Search is Flaky

**Comment by pinkbubba** [comment] 2024-09-06 13:52
I'm also interested in this feature. I installed onemore to make it easier for creating links between pages to try and use onenote as second brain. Hoping it will be fixed in the future. Onemore is very nice otherwise.

**Comment by Cossackx** [comment] 2024-09-17 13:40
👏This is definitely my favorite OneMore feature. I refresh "Check for Updates" daily.

https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGN1YnExdHR3bDdtN2xkaWdzMWljZHl4NDJ2aWYxMTJueHRudGppeCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/l2YWluoNgk342F3k4/giphy.gif

**Closed** 2024-11-03 00:48 UTC
Labels: bug, released
