### ISSUE TITLE
Insertion and style application break displayed equations

### ISSUE THREAD

**Issue by wheird-lee** [stevencohn/OneMore#1244] opened 2024-01-04 12:59 UTC
# Problem to Solve
I had written several equations on a OneNote page.

After I inserted a code block using onemore (6.01) on that page, however, all displayed equations were broken.

The same bug reproduces after inserting other texts including contents, and reproduces after applying styles.

# To Reproduce

1. Write a displayed equation on a page
2. Inserting some texts (contents, or code blocks, etc.) or applying any style using onemore.
3. See error

# Expected Behavior

inserting texts or applying styles should not change irrelevant texts.

# Screenshots
1. a displayed equation
![image](https://github.com/stevencohn/OneMore/assets/54490105/fc9fa5d0-738c-4f75-bbff-ef2261191842)

2. the  displayed equation was broken after inserting some texts using onemore.
![image](https://github.com/stevencohn/OneMore/assets/54490105/801c3e84-c88c-496d-ac64-85ca72df6153)
3. It seems the equation was converted into what the picture below shows. 

![image](https://github.com/stevencohn/OneMore/assets/54490105/9d838658-4564-4140-8d5c-899a4a06f406)

# Environment

 - OneNote Version: 16.0.17029.20068 
 - OneMore Version: 6.01

**Comment by stevencohn** [comment] 2024-01-04 13:06
Duplicate of #1128

**Closed by stevencohn** 2024-01-04 13:06 UTC
Labels: bug, duplicate
