### ISSUE TITLE
Preview Markdown - Syntax highlighting (fenced code blocks)

### ISSUE THREAD

**Issue by seaspeak** [stevencohn/OneMore#1410] opened 2024-05-26 18:58 UTC
# Problem to Solve

Fenced code blocks cause error.

# To Reproduce

use the following text, and then preview it

\```python
import sys
\```

# Expected Behavior

It is extended-syntax (https://www.markdownguide.org/extended-syntax/#fenced-code-blocks). Some will colorize it, like github; or ignore it.

# Screenshots

![image](https://github.com/stevencohn/OneMore/assets/8821870/97030c79-3c3e-48e7-95c8-63ab863cb3fc)

# Environment (if applicable)

 - OneNote Version: Office 2021 64bit
 - OneMore Version 6.4.0

# Additional Context

**Comment by stevencohn** [comment] 2024-05-26 19:03
Unable to reproduce. Do you have the log file? `C:\Users\USERNAME\AppData\Local\Temp\OneMore.log`

![image-demo](https://github.com/stevencohn/OneMore/assets/9964757/05a2aea0-2340-4de7-a45e-f4476bb390ff)

**Comment by seaspeak** [comment] 2024-05-26 19:20
04|03:19:22.912| Running command PreviewMarkdownCommand
04|03:19:22.939| Error running command PreviewMarkdownCommand
04|03:19:22.939| System.TypeLoadException
Message: Could not load type 'System.Numerics.Vector' from assembly 'System.Numerics.Vectors, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Source: System.Memory
StackTrace:    at System.SpanHelpers.SequenceEqual(Byte& first, Byte& second, NUInt length)
   at Markdig.Helpers.TransformedStringCache.EntryGroup.TryGet(ReadOnlySpan`1 inputSpan)
   at Markdig.Helpers.TransformedStringCache.Get(ReadOnlySpan`1 inputSpan)
   at Markdig.Parsers.FencedBlockParserBase`1.DefaultInfoParser(BlockProcessor state, StringSlice& line, IFencedBlock fenced, Char openingCharacter)
   at Markdig.Parsers.FencedBlockParserBase`1.TryOpen(BlockProcessor processor)
   at Markdig.Parsers.BlockProcessor.TryOpenBlocks(BlockParser[] parsers)
   at Markdig.Parsers.BlockProcessor.TryOpenBlocks()
   at Markdig.Parsers.BlockProcessor.ProcessLine(StringSlice newLine)
   at Markdig.Parsers.MarkdownParser.ProcessBlocks(BlockProcessor blockProcessor, String text)
   at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
   at River.OneMoreAddIn.Commands.OneMoreDig.ConvertMarkdownToHtml(String path, String markdown)
   at River.OneMoreAddIn.Commands.PreviewMarkdownCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [System.Memory] System.SpanHelpers::SequenceEqual()

**Comment by seaspeak** [comment] 2024-05-26 19:28
Can you also the following text:
1. input the following text
code
<tab>

2. Preview.

![image](https://github.com/stevencohn/OneMore/assets/8821870/10d97e69-a632-4711-90f8-45c1461b8cd0)

**Comment by stevencohn** [comment] 2024-05-27 01:55
Might be an installer problem. I'll have to check it next week.

**Comment by stevencohn** [comment] 2024-07-08 18:25
Exception will be fixed in the next release of OneMore. Syntax highlighting will not be supported.

**Comment by stevencohn** [comment] 2024-07-15 14:38
Duplicate of, and resolved by, #1429.
Closing this ticket and releasing under 1429 instead.

**Closed** 2024-07-21 13:29 UTC
Labels: bug, released
