### ISSUE TITLE
Implement onemark like live update of markdown doc inside onenote.

### ISSUE THREAD

**Issue by bayeslearner** [stevencohn/OneMore#1073] opened 2023-07-24 05:53 UTC
# Problem to Address

A prevalent issue among OneNote users is the inability to view and update embedded markdown documents within the application effectively. Onemark, a separate licensed software, handles this issue with ease, enhancing its appeal as a robust knowledge management tool. Having Onemark's functionality replicated within OneMore could substantially enhance OneNote's status as the ultimate, all-in-one solution for knowledge management.

# Proposed Feature/Solution

OneMore's existing capabilities, particularly its ability to import and export between OneNote and markdown, lay a solid foundation for the feature we propose. We recommend implementing a live update mechanism for markdown documents within OneNote, akin to the features offered by Onemark.

This feature would allow users to observe their edits in real-time as they update their markdown documents within OneNote, resulting in significant boosts in productivity and user satisfaction with the tool. It could also attract users currently leaning towards other software due to this specific functionality.

One added benefit that can't be overlooked is the convenience factor. Users would no longer need to juggle between OneMore and Onemark to achieve their objectives, as all their needs could be met within OneMore. This seamless user experience could substantially enhance OneMore's appeal to both existing and potential users.

Given OneMore's demonstrated competency in markdown and OneNote interoperability, this feature would be a logical and beneficial extension of the software's capabilities. By integrating it, we can elevate OneMore's standing and reinforce its reputation as a comprehensive tool for efficient knowledge management.

**Comment by stevencohn** [comment] 2023-07-24 22:02
Duplicate of #1021, #1028

Will not implement

**Closed by stevencohn** 2023-07-24 22:02 UTC
Labels: duplicate, wontfix
