### ISSUE TITLE
"Tag Page" and "Find Tagged Page" not working.

### ISSUE THREAD

**Issue by emuell1696** [stevencohn/OneMore#1287] opened 2024-01-24 13:28 UTC
# Problem to Solve
The function "Tag Page" and "Find Tagged Page" are not working as expected on my Windows 11 (ARM) Surface Pro X. On my other Surface Pro 9 (Intel) the functionality is given.
I can tag the page using the "Tag Page" dialogue, and the little tag symbol is visible on the note itself, but later I am not able to find the page using "Find Tagged Page"

# To Reproduce

1. Go to 'Tag Page.'
2. Enter a Tag for the Page
![image](https://github.com/stevencohn/OneMore/assets/32419212/bce9b883-5a64-4110-a037-767e56bb3904)
3. The new tag can be seen on the note.
![image](https://github.com/stevencohn/OneMore/assets/32419212/50a95a2c-4e40-437e-8e37-8181b83d9b0e)
4. Click on 'Find Tagged Page' and search for 'tagtest' -> nothing is being found, and no suggestions appear below the search field.
![image](https://github.com/stevencohn/OneMore/assets/32419212/e593600b-b01b-4efd-beb6-2b012cb63c81)

# Expected Behavior

"Find Tagged Pages" should find all notes with the tag "tegtest". "Find Tagged Pages" should also display a list of the last used tags below the text entry field.

# Environment (if applicable)

 - OneNote Version: O365, 64 bit ARM (!)
 - OneMore Version 6.1.0

# Additional Context
Everything else seems to work fine on my Surface Pro X ... also the new functionality with the "##tags".

**Comment by stevencohn** [comment] 2024-01-24 13:45
Duplicate of #1219.

Background: This relies on Windows search which is not always up to date. Generally, the search index is update quickly so you should be able to find tags after a few minutes. But sometimes, I've found this to take hours.

@emuell1696 Quick question if you don't mind... Is there a reason to use the Tagged Page feature over the new Hashtag feature?

**Comment by emuell1696** [comment] 2024-01-24 13:55
Windows Search can be "slow" from time to time, you are right - I can see the "delay" on my other client, where the functionality is working well. But on the Surface the tags are not searchable even after days, or better weeks. I am using OneMore un the Surface X since last November, and never could find a tag on that device. Tried several re-installs of your tool - nothing.
Could it be related to the ARM architecture? 
I would prefer to use the "old" Tagged Page feature because I already started using it on the Intel machine. And to be honest, it also looks nicer with the little tag on top of the page - but that is only cosmetic.

**Comment by stevencohn** [comment] 2024-01-24 14:24
I don't have any ARM machines so can't answer your question unfortunately.

I'm considering a migration option where OneMore can convert all Page Tags to hashtags and keep them up there in that little box with the tag. That would let me deprecate the old clunky functionality and make it more performant and extensible in the future.

**Comment by stevencohn** [comment] 2024-04-29 10:18
Page tags are now deprecated as of v6.2.1. That version helps you upgrade your page tags to hashtags and then disables the page tag commands. Those commands will be removed in a later release of OneMore.

**Closed by stevencohn** 2024-04-29 10:18 UTC
Labels: bug, duplicate, wontfix
