### ISSUE TITLE
Scripting Interface

### ISSUE THREAD

**Issue by edogd** [stevencohn/OneMore#27] opened 2020-08-07 16:49 UTC
One of the greatest limitations of OneNote is a lack of a scripting interface.  I wonder if a scripting interface, similar to what Onetastic or other office apps have can be added.   There might be some packages which could be leveraged to achieve this.  The interface could provide and object to the application and another object to the current document a long with some access to some xml functions and basic program flow control.  I don't know if there is one such package already for VBscript or even python.

**Comment by stevencohn** [comment] 2020-08-08 12:31
This is something I'd need to consider at length. It would make OneMore something quite different than what it started out to be and would most certainly evolve to match suspiciously close parity with Onetastic, which already exists and works quite well. OneMore is small and efficient and focused. I'll continue to add features but a scripting engine is ambitious at least. If I find (or someone is adventurous enough to come up with a small and lightweight proposal)... maybe.

My main goal for OneMore is to add "one-click" features that users (primarily myself) would find immediately useful without needing to learn something new or obtuse. I've always wanted very basic Excel-like calculations in tables without embedding an actual Excel table in the page, which in my opinion is a bit clunky and heavy. So in that vain, my next feature set is going to add basic calculations to tables - sum, average, etc.

[Editorial: Quite honestly, I get a lot of users who need help finding the installer on the Releases page! So my take away from that is that there are a lot of users who want friendly features and might be terrified of scripting. Of course, I realize the other half of users are real Github geeks so.... what do I know?! ;-) ]

**Comment by 1001QAdotNET** [comment] 2020-08-11 22:54
I have an big issue with the licensing model that Onetastic adopted
They are forcing me to pay every year 15USD after paying an upfront cost of 60-70USD for the first year
What if I don't want any other improvements and I am just actually buying the software for running only one simple script (I need to indent/unindent any paragraph that I mark with a character like ◄ / ►  or ident any paragraph that does not contain ◄

**Comment by stevencohn** [comment] 2020-08-12 14:50
Have you tried this? It's kind of a hack but it seems to work...

Create an Auto-correct rule that turns your chosen character sequence (e.g. "\t") into a regular TAB:
1. Open Notepad and type one TAB. Select it and copy it.
2. Go to OneNote and click File | Options | Proofing | AutoCorrect Options
3. In the dialog, put your desired sequence of characters (e.g. \t into the "Replace:" field.
4. Paste the TAB that you copied from Notepad into the "With:" filed. Click Add.
5. Now, any \t followed by a SPACE will be replaced by a regular TAB.

**Comment by 1001QAdotNET** [comment] 2020-08-12 15:49
Nice trick I might apply it for something else
I should have been more specific, for now I am indenting any paragraph that does not contain a ► which I usually put in the kine that would become the hearer of that section created by indenting. This should be a piece of cake to deliver as build in script in your addon (if you want to mate it flexible allow indentation level, variable marker (instead of ►) and make it work both ways indent deindent

**Comment by stevencohn** [comment] 2020-08-12 16:02
When you press TAB in OneNote, it indents the current paragraph and SHIFT-TAB will de-indent the paragraph. You can also selected a number of paragraphs and press TAB or SHIFT-TAB. I'm probably missing something, but isn't that easier that or at least as easy as adding a black-right-pointer char and then running a script? What would the script do beyond that? Do you want the "header line" to be formatted as a Header as well? Do you want to keep or remove the black-right-pointer?

Sorry, just trying to understand a little more because a tenet of OneMore is to not reinvent the wheel - if there's a reasonable alternative already in OneNote, is it worth adding another feature to OneMore?

**Comment by 1001QAdotNET** [comment] 2020-08-12 16:55
Imagine a very long web page (an online Oreilly book usually has that, a chapter is a very long web page)
There is text blocks and there is headers
Under a header you can have multiple text blocks 
It will be easier to mark 20 headers ans run the script than to go to each text block and press tab to indent it

**Comment by 1001QAdotNET** [comment] 2020-08-18 19:45
Any chance to have that basic and easy functionality added 😀

**Comment by stevencohn** [comment] 2020-08-18 22:14
I'll take a look. What do you think about just keying off of Headings instead of a special character? pros/cons? 

It could indent based on heading#, so below Heading 1 would have no indent, below Heading 2 would have "2" indents, etc.?

Do you think all content under such "headings" should be indented regardless of what it is or whether it is already indented?

**Comment by 1001QAdotNET** [comment] 2020-08-24 17:03
That could be a default approach and time saving
The issue is that when you copy and paste the text might have pseudo heading (they are using specific format but not tied to H1, H2 and so on tags)
Also you might or might not want to indent certain paragraphs
Reversing the indentation might not be so easy without a marker

What we are looking for is a very flexible way to mass change the indentation of paragraphs
Of course this could be made as sophisticated as you want (ex traversing the text to collect the type of formatting and present the user  with a list of formats used (css styles) and ask the user which format to be indented -this is to avoid the issues caused by not using H1-H7 headings

**Comment by stevencohn** [comment] 2020-09-17 11:12
Scripting is not something I'm interested in tackling at this time.

But the paragraph indentation feature has been added.

**Comment by 1001QAdotNET** [comment] 2020-09-17 15:08
Thank you works great
Any chance you can modify this to have memory (retain the settings for indentation once they are set)
There seems to be a bug or a design issue.  Sometimes there is an empty line just below the paragraph, that needs to be indented too in order to be able to collapse the paragraph otherwise the user needs to review each paragraph and indent that line manually

Also if I might suggest a slight improvement, if you could add a field there where the user can set how many tabs (indentations level) should be applied. If the number is negative the indentation could turn into deindentation Great idea to use tags

There also seem to be problems to select tags that are in the right columns of the tag selection pannel
The more you go to the right the more difficult is to select the tag (there is an offset between mouse and the focus on the icon)}
See this animated gif...wait till you see movement on the screen nothing happens in the first 2-3 seconds
[https://i.imgur.com/gZP8f8Y.gif](url)

I know that you are busy, please deal with these as you have time 
thank you again for all this great work

**Comment by 1001QAdotNET** [comment] 2020-09-17 16:31
It seems that the option to remove empty lines and paragraphs will deal with the particular issue that stops the collapsing that I mentioned above so scratch that off the list if you wish
The spacing (a empty line indented below the tagged paragraph or header) is useful to improve readability so if the indentation can be applied to these empty lines it would be great. If not then I can work with the above workaround

tank you again

**Comment by stevencohn** [comment] 2020-09-17 18:53
I though I had fixed that mouse-offset problem you noticed. Sorry about that. It's probably just a simple rounding error. I'll take a look

**Comment by 1001QAdotNET** [comment] 2020-09-17 19:27
Do't be sorry, your work comes free and on a voluntary basis we have no expectations and take everything as a generous gift

**Comment by stevencohn** [comment] 2020-09-17 22:18
So I can't seem to reproduce it. It's off by 1 or 2 pixels but certainly not 16 or 20 as it looks like in your animated gif.
I've tested it on a normal 96dpi display at 100% scaling and a high 144dpi display at 150%.

What is your setup?

**Comment by 1001QAdotNET** [comment] 2020-09-17 22:46
https://i.imgur.com/OsNH1zc.gif

This one is on a monitor set for 1900x1200    Custom factor scale 200%
The previous one was on a monitor set for 1920x1080 at 175%
Windows 10,  OneNote 2013 x86

**Comment by 1001QAdotNET** [comment] 2020-09-18 01:51
re the empty div below the paragraph marked with a tag: it seems that OneMore is adding that when it is indenting the text

**Comment by stevencohn** [comment] 2020-09-19 01:44
Indentation is now fixed. And the Outline dialog settings will be preserved (can be reset to blanks from the dialog's system menu)

These will be available in the next release.

**Comment by 1001QAdotNET** [comment] 2020-09-19 11:30
Great, thank you!

**Comment by stevencohn** [comment] 2020-09-20 17:50
Now available in v2.13 https://github.com/stevencohn/OneMore/releases/latest

**Comment by stevencohn** [comment] 2020-10-08 13:47
A couple of subsequent features were completed from this ticket but I've decided not to pursue the main title - scripting. Closing this

**Closed by stevencohn** 2020-10-08 13:47 UTC
Labels: enhancement

**Comment by 1001QAdotNET** [comment] 2020-10-09 03:59
I am going to begin testing the feature that allows the user to run external plugins/scripts that take as argument the XML form of the onenote page ....IMHO that can be leveraged to use any sort of scripting 

If that is added to the quick access bar and a short cut is asigned there the user is good to go

**Comment by stevencohn** [comment] 2020-10-09 12:16
I'll be interested to know what you come up with. If it's seems useful to a wider audience, I'll consider adding a built-in function. I'll keep my eye out for new feature requests...
