### ISSUE TITLE
Collapse/Expand Paragraph

### ISSUE THREAD

**Issue by megamorphg** [stevencohn/OneMore#904] opened 2023-02-14 02:03 UTC
# Problem to Solve
I like the ability to collapse/expand sections and use it to hide large sections of notes and sub-notes.
I have the tendency to have very long pages and would like to have an ability to mass collapse/expand sections preferably to a specified level.

# New Feature/Solution
"Collapse/Expand Paragraphs" option that gives a dialog box to enter a collapse/expand "Level". The number entered, collapses all paragraphs to the level entered.
Level 1
  Level 2
    Level 3

- Default = 1
- "Recursive" checkbox to collapse/expand recursively throughout all levels. Default = false
- Works with selections, too, determining the levels automatically based on the selection
- Would also be great to have a "quick mode" without a dialog box so that can easily just repeat the last action without a dialog box

## Alternative Solutions

Manually double-clicking the needed paragraph indicators on the left. Only option now.
![image](https://user-images.githubusercontent.com/1782353/218619666-3e41287f-09a6-4ebd-8a68-72f9f3952f72.png)

**Comment by stevencohn** [comment] 2023-02-14 02:08
OneMore does have a feature where you can save the current state of a page. Then you can expand/collapse paragraphs. Then you can restore the saved state. State is stored in a per-page basis so you can save a different state for each page.

Is that close enough?

**Comment by julie777** [comment] 2023-02-14 03:33
OneNote already has keyboard shortcuts to expand and collapse.

`<alt><shift>-MOD` 
where 
- MOD is + or - to decrease or increase the level of indentation
- MOD is a number between 1 and 9 which specifies the number of levels expanded (1 is everything collapsed)

The expand/collapse will act on the hierarchy with the cursor in it, or the entire selection. So if I want to collapse every collapsable item on the page:
1. `<ctrl>-a` probably multiple times to keep expanding the selection to the entire page.
2. `<ctrl>-1` which will collapse everything

**Comment by stevencohn** [comment] 2023-02-15 03:13
@megamorphg can you show an example of the problematic table? I wasn't able to reproduce it

**Comment by julie777** [comment] 2023-02-15 23:59
I did many experiments and determine the rules for expand and collapse used by OneNote

Rules for expand/collapse

1. Handles are treated as a scope that always includes the entirety of what is highlighted when you click on one. It doesn't matter if it is showing highlighted or not when you double click. But double-click only affects the state of the item next to the handle.
	
	Double Click on handle
		Collapses that item
		Expands that item
	
2. Collapse/Expand Shortcuts act on the entire outline containing the cursor. The cursor position is ignored as is any partial selection of the outline.

Shortcuts available are (where S is shorthand for `<alt><shift>`
S0	Always fully expands the full outline hierarchy
S1..9	Collapse to that level hiding what is below
S- 	Alias for S1
S+	Alias for S0

Note: I did at one point have S9 expand the item and leave subs that were collapsed before S1 stay collapsed, but I am not able to reproduce it now.

A table inside an outline is treated as a single paragraph and its contents are ignored unless the cursor is inside a cell and the cell is not selected. (Different than selecting text in the cell) 
If the entire cell is selected then the cursor is treated as in the "table paragraph" as opposed to being in the cell and therefore rule 2 applies.

There is no way to treat the contents of a table as a big group containing the contents of each of the cells and perform collapse and expand on multiple cells at the same time. The cursor is either in a cell, or in a paragraph. As far as expand/collapse there is no such thing as a table.

3. cursor in a cell

If the cursor is within a cell then the current scope of operation is the text in the cell and rule 2 applies. 

4. Selection of more than a single outline. This can be a container, or multiple containers, etc. You can think of this selection as an imaginary outline with at level 0 and containing all the other outlines.

Because there is no such thing as outline 0 you can only collapse to level one, you will always have all separate outline roots visible. Each individual outlines in the selection are treated as such and collapse/expand works for all of them in unison. 

Exception:
When multiple outlines are selected S- and S+ don't work.
In addition, if you select a container which is technically and outline in the OneNote representation it has the same exception that S- and S+ don't work, leaving S0..9 for use.

Note: when a cell is fully selected it look similar to a container that is fully selected, but S0..9 work on the container but work on the outline containing the cell.

**Comment by julie777** [comment] 2023-02-16 00:01
I spent way too much time writing and rewriting the above and now the day is almost gone, so I just submitted it. I am still working on a better explanation.

I am struggling to provide a simple explanation that both allows us to work with the implementation and would allow a OneNote user to understand. The difference between the XML and what you see on the page can be a little confusing.

**Comment by stevencohn** [comment] 2023-02-16 00:18
I've already assessed the defect. It's actually quite simple. There is no need for such a lengthy explanation. Not that it's not appreciated but, really, I got this.

**Comment by stevencohn** [comment] 2023-02-16 00:20
I accidentally closed it, reopening

**Comment by stevencohn** [comment] 2023-02-16 00:32
Resolved, the problem didn't have anything to do with the Cell. It was the fact that @megamorphg was collapsing a List parent which the [ExpandoCommand](https://github.com/stevencohn/OneMore/blob/main/OneMore/Commands/Page/ExpandoCommand.cs#L77) didn't take into account.

**Comment by stevencohn** [comment] 2023-02-16 00:34
@julie777 I suggest getting familiar with the [OneNote XML schema](https://github.com/stevencohn/OneMore/blob/main/Reference/0336.OneNoteApplication_2013.xsd). It would save quite a lot of time rather than trying to reverse engineer the structure entirely by observing changes in the XML.

**Comment by julie777** [comment] 2023-02-16 21:25
> Alt+Shift+Minus and Alt+Shift+Plus

I did include them using S- and S+ because I didn't want to use code blocks for all my mentions of them.

**Closed** 2023-02-19 00:24 UTC
Labels: bug, released
