### ISSUE TITLE
Quick access to autocorrect options -  to add words to replace text as type

### ISSUE THREAD

**Issue by dpostl** [stevencohn/OneMore#460] opened 2022-02-21 23:22 UTC
I have to go to file, options, proofings, autocorrect options to add a new fix to autocorrect. It takes a long time and it's not practical to do during class.

I would like a button to go straight into autocorrect options.

I can't think of an alternative... I can't find a stand-alone autocorrect program that I can plug in. And I can't find how to import a massive amount of fixes. 

I think I'm thinking of something like described here: https://answers.microsoft.com/en-us/msoffice/forum/all/macro-for-autocorrect/310abfe5-a462-4aa9-bfb8-3e0371943cf5

Thank you for providing OneMore in general and considering this possible feature.

**Comment by stevencohn** [comment] 2022-02-21 23:31
OneMore is built on a specific API published by Microsoft for OneNote extensions. It does not give me access to the autocorrect library or those bits of UI.

However, I do have an open issue, #278, to implement something very similar, Auto Text. With this option, you could add a short phrase, press a key sequence, and it would expand into a longer or different phrase. This could be use to "correct" common misspellings as well although not as integrated as the built-in autocorrect feature.

So for now, I'm calling this a duplicate of #278

**Closed by stevencohn** 2022-02-21 23:31 UTC
Labels: duplicate
