### ISSUE TITLE
Win11 OneMore for Onenote Issue

### ISSUE THREAD

**Issue by pkennedy29** [stevencohn/OneMore#1428] opened 2024-06-07 14:20 UTC
When trying launch any OneMore command in OneNote and we are getting "Error Running "Commandname" see log file for details.

We have uninstalled and reinstalled, under local pc admin, and still get the error. Running IQ.ps1 says there are missing reg entries. Attached are the install log file and the OneMore log file.

Another colleague is experiencing the same issue. 

Thnak you for your assistence in getting this Isuue fixed. We really like your software and find it very helpful.  

Pat

[onemore_setup.log](https://github.com/user-attachments/files/15740847/onemore_setup.log)
[OneMore.log](https://github.com/user-attachments/files/15740875/OneMore.log)
# Problem to Solve

# To Reproduce

# Expected Behavior

# Screenshots

# Environment (if applicable)

 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment] 2024-07-11 02:05
Please check the Enabled property under this Windows System Registry key:

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy`

1. Close OneNote
2. Set the Enabled property to 0
3. Restart OneNote
4. Try commands

**Comment by stevencohn** [comment] 2024-07-11 10:44
Duplicate of $1426. Attached PR for reference.

**Closed** 2024-07-21 13:29 UTC
Labels: bug, duplicate, released
