### ISSUE TITLE
Wildcard searches

### ISSUE THREAD

**Issue by onlytanmoy** [stevencohn/OneMore#1247] opened 2024-01-07 11:37 UTC
Hi, hope you doing well.

I believe OneNote searches from the start of the word, so if I search on 'Some', OneNote will find any words that start with Some, as in Something Somewhere, etc. However if I search on 'ome' OneNote only finds words that BEGIN with "ome", it does not perform wildcard searches. Is there any feature in OneMore that will allow me to perform wildcard searches or any workaround you are aware of?

**Comment by stevencohn** [comment] 2024-01-07 12:33
Duplicate of #1084

**Closed by stevencohn** 2024-01-07 12:33 UTC
Labels: duplicate
